/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FOODIE.java
 *
 * Created on 10 Jul, 2020, 7:41:39 PM
 */

/**
 *
 * @author Hemanth S
 */
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FOODIE extends javax.swing.JFrame {

    /** Creates new form FOODIE */
    public FOODIE() {
        initComponents();
    }
    Connection con = null;
Statement stmt = null;
ResultSet rs = null;
DefaultTableModel tm = null;
String currentUserID = null;
String currentRestaurant=null;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        phoneTF1 = new javax.swing.JTextField();
        PF1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        loginFrame = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        actualLoginButton = new javax.swing.JButton();
        phoneTF2 = new javax.swing.JTextField();
        PF2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        dashboard = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        menuFrame = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodItemsList = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JTextField();
        orderFrame = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();

        signUpFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        signUpFrame.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel2.setText("SIGN UP!");

        jLabel3.setText("Enter Name:");

        jLabel4.setText("Enter Phone Number:");

        jLabel5.setText("Enter Password:");

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        phoneTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTF1ActionPerformed(evt);
            }
        });

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpFrameLayout = new javax.swing.GroupLayout(signUpFrame.getContentPane());
        signUpFrame.getContentPane().setLayout(signUpFrameLayout);
        signUpFrameLayout.setHorizontalGroup(
            signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpFrameLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(signUpFrameLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PF1))
                    .addGroup(signUpFrameLayout.createSequentialGroup()
                        .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTF)
                            .addComponent(phoneTF1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpFrameLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpFrameLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(174, 174, 174))
        );
        signUpFrameLayout.setVerticalGroup(
            signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpFrameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        loginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginFrame.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel6.setText("LOGIN");

        jLabel7.setText("Enter Phone number:");

        jLabel8.setText("Enter Password:");

        actualLoginButton.setText("LOGIN");
        actualLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel6))
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PF2)
                            .addComponent(phoneTF2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(actualLoginButton)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(59, 59, 59)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phoneTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(PF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(actualLoginButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jButton2.setText("jButton2");

        jTextField1.setText("jTextField1");

        dashboard.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        dashboard.setMinimumSize(new java.awt.Dimension(400, 300));
        dashboard.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dashboardWindowActivated(evt);
            }
        });

        jLabel9.setText("FOODIE!!");

        jLabel10.setText("SELECT A RESTAURANT:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select a Restaurant --", " " }));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard.getContentPane());
        dashboard.getContentPane().setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel9))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(okButton)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(55, 55, 55)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(76, 76, 76))
        );

        menuFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        menuFrame.setMinimumSize(new java.awt.Dimension(400, 300));
        menuFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                menuFrameWindowActivated(evt);
            }
        });

        jLabel11.setText("MENU");

        jLabel12.setText("Select Items:");

        jButton3.setText("ORDER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        foodItemsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "--Select items--" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(foodItemsList);

        jButton4.setText("Check Total Price");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setText("Total Cost:");

        totalLabel.setText(" ");

        javax.swing.GroupLayout menuFrameLayout = new javax.swing.GroupLayout(menuFrame.getContentPane());
        menuFrame.getContentPane().setLayout(menuFrameLayout);
        menuFrameLayout.setHorizontalGroup(
            menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFrameLayout.createSequentialGroup()
                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuFrameLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel11))
                    .addGroup(menuFrameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuFrameLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(69, 69, 69)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        menuFrameLayout.setVerticalGroup(
            menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(57, 57, 57)
                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(menuFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(221, 221, 221)
                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(menuFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(45, 45, 45))
        );

        orderFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        orderFrame.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel14.setText("Cart-Check Out");

        jButton5.setText("Close ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Complete Address: ");

        addressArea.setColumns(20);
        addressArea.setRows(5);
        jScrollPane2.setViewportView(addressArea);

        javax.swing.GroupLayout orderFrameLayout = new javax.swing.GroupLayout(orderFrame.getContentPane());
        orderFrame.getContentPane().setLayout(orderFrameLayout);
        orderFrameLayout.setHorizontalGroup(
            orderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderFrameLayout.createSequentialGroup()
                .addGroup(orderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderFrameLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel14))
                    .addGroup(orderFrameLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(orderButton)
                        .addGap(75, 75, 75)
                        .addComponent(jButton5))
                    .addGroup(orderFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        orderFrameLayout.setVerticalGroup(
            orderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderFrameLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel14)
                .addGap(37, 37, 37)
                .addGroup(orderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(orderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderButton)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FOODIE");

        loginButton.setText("LOG IN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        signUpButton.setText("SIGN UP");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(signUpButton)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(signUpButton))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
this.dispose();
signUpFrame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
this.dispose();
loginFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void phoneTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTF1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_phoneTF1ActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nameTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Name = nameTF.getText();
String  Phone= phoneTF1.getText();
String pwd = new String(PF1.getPassword());
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "");
    stmt = con.createStatement();
    String sql = "INSERT INTO Foodie(Name, Phone, Pass, DOJ) VALUES('" + Name + "', '" + Phone + "', '" + pwd + "', curdate());";
    System.out.println(sql);
    stmt.executeUpdate(sql);
    JOptionPane.showMessageDialog(rootPane, "Congrats! Account created successfully!");
    signUpFrame.dispose();
    this.setVisible(true);
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualLoginButtonActionPerformed
String uid = phoneTF2.getText();
String pwd = new String(PF2.getPassword());
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "");
    stmt = con.createStatement();
    String sql = "SELECT Pass FROM Foodie WHERE Phone = '" + uid + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
    String pass = rs.getString(1);
    if(pwd.equals(pass)){
        loginFrame.dispose();
        dashboard.setVisible(true);
    }
    else{
    JOptionPane.showMessageDialog(null, "See, your userID or password is wrong. Try again!");
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_actualLoginButtonActionPerformed

    private void dashboardWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dashboardWindowActivated
currentRestaurant=null;
        jComboBox1.removeAllItems();
        jComboBox1.addItem("--Select Restaurant--");
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT Name FROM Restaurants ORDER BY Sr_No ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
        jComboBox1.addItem(rs.getString("Name"));
    }
    jComboBox1.setSelectedItem("--Select Restaurant--");
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardWindowActivated

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
String restaurant = (String)jComboBox1.getSelectedItem();
if(jComboBox1.getSelectedIndex()==0 || jComboBox1.getSelectedIndex()==-1){
    JOptionPane.showMessageDialog(null, "please select a restaurant");
}
else if(restaurant == null || restaurant.equals("")){
    JOptionPane.showMessageDialog(null, "please select a restaurant");
    return;
}
else{
      currentRestaurant=restaurant;
    dashboard.dispose();
    menuFrame.setVisible(true);}
// TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    private void menuFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_menuFrameWindowActivated
          foodItemsList.setModel(new DefaultListModel());
        DefaultListModel lm = (DefaultListModel)foodItemsList.getModel();
        lm.removeAllElements();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT Title FROM Menu WHERE restaurant = '" + currentRestaurant + "';";
              System.out.println(sql);
            rs = stmt.executeQuery(sql);
            while(rs.next()){
            lm.addElement(rs.getString("Title"));
            System.out.println(rs.getString("Title"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_menuFrameWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int total=0;
        Object namesOfItems[] = foodItemsList.getSelectedValues();
        for(int i = 0; i < namesOfItems.length; i++)
        {
             try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT price FROM Menu WHERE Title = '" + namesOfItems[i] + "' AND restaurant='"+currentRestaurant+"';";
              System.out.println(sql);
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                System.out.println(total);
                total=total+rs.getInt("price");}
             rs.close();
    stmt.close();
    con.close();
             }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
        }
        totalLabel.setText(""+ total);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(totalLabel.getText().isEmpty()){
System.out.println("select atleast one item");
}
else{
menuFrame.dispose();
orderFrame.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
String address= addressArea.getText();
if(addressArea.getText().isEmpty()){
    JOptionPane.showMessageDialog(null,"Please Enter address");
}
else{
JOptionPane.showMessageDialog(null, "Order Successful ");
orderFrame.dispose();
dashboard.setVisible(true);
}// TODO add your handling code here:
}//GEN-LAST:event_orderButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FOODIE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PF1;
    private javax.swing.JPasswordField PF2;
    private javax.swing.JButton actualLoginButton;
    private javax.swing.JTextArea addressArea;
    private javax.swing.JFrame dashboard;
    private javax.swing.JList foodItemsList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JFrame menuFrame;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton okButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JFrame orderFrame;
    private javax.swing.JTextField phoneTF1;
    private javax.swing.JTextField phoneTF2;
    private javax.swing.JButton signUpButton;
    private javax.swing.JFrame signUpFrame;
    private javax.swing.JTextField totalLabel;
    // End of variables declaration//GEN-END:variables

}
