import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABC_Car_Rentals.java
 *
 * Created on 19 Apr, 2020, 4:09:51 PM
 */

/**
 *
 * @author GAURI BAOKAR
 */
public class ABC_Car_Rentals extends javax.swing.JFrame {

    /** Creates new form ABC_Car_Rentals */
    public ABC_Car_Rentals() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JFrame();
        DeluxeCar = new javax.swing.JRadioButton();
        SDeluxeCar = new javax.swing.JRadioButton();
        OrCar = new javax.swing.JRadioButton();
        GDradio = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        daysfield = new javax.swing.JTextField();
        calculatebutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        amtfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gdfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pswd = new javax.swing.JPasswordField();
        OK = new javax.swing.JButton();

        dashboard.setMinimumSize(new java.awt.Dimension(400, 300));

        buttonGroup1.add(DeluxeCar);
        DeluxeCar.setText("Deluxe Car");
        DeluxeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeCarActionPerformed(evt);
            }
        });

        buttonGroup1.add(SDeluxeCar);
        SDeluxeCar.setText("Semi Deluxe Car");
        SDeluxeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDeluxeCarActionPerformed(evt);
            }
        });

        buttonGroup1.add(OrCar);
        OrCar.setText("Ordinary Car");

        GDradio.setText("Guide Required");

        jLabel3.setText("Car required for number of days:");

        daysfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysfieldActionPerformed(evt);
            }
        });

        calculatebutton.setText("Calculate");
        calculatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebuttonActionPerformed(evt);
            }
        });

        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount:");

        jLabel5.setText("Guide Charges:");

        jLabel6.setText("Total Amount:");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard.getContentPane());
        dashboard.getContentPane().setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeluxeCar)
                            .addGroup(dashboardLayout.createSequentialGroup()
                                .addComponent(SDeluxeCar)
                                .addGap(65, 65, 65)
                                .addComponent(GDradio))
                            .addComponent(OrCar)
                            .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dashboardLayout.createSequentialGroup()
                                    .addComponent(calculatebutton)
                                    .addGap(47, 47, 47)
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exitbutton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dashboardLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(daysfield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalfield)
                            .addComponent(gdfield)
                            .addComponent(amtfield, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(DeluxeCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDeluxeCar)
                    .addComponent(GDradio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrCar)
                .addGap(33, 33, 33)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(daysfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatebutton)
                    .addComponent(exitbutton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ABC CAR RENTALS");

        jLabel2.setText("Enter Password:");

        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });

        OK.setText("OK ");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OK)
                    .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(OK)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
String password=new String(pswd.getPassword());
if(password.equals("hello"))
{
    this.dispose();
    dashboard.setVisible(true);
}
else
{
    JOptionPane.showMessageDialog(null,"Wrong Password!");
}

}//GEN-LAST:event_OKActionPerformed

    private void DeluxeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeluxeCarActionPerformed

    private void SDeluxeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDeluxeCarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SDeluxeCarActionPerformed

    private void calculatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebuttonActionPerformed
        int numberOfDays=Integer.parseInt(daysfield.getText());
        int amt=0;
        if(DeluxeCar.isSelected()){
            amt=numberOfDays*1000;
        }
        else if(SDeluxeCar.isSelected()){
            amt=numberOfDays*800;
        }
        else if(OrCar.isSelected()){
            amt=numberOfDays*700;
        }
        int guideCharges=0;
        if(GDradio.isSelected())
            guideCharges=numberOfDays*500;
        int total=amt + guideCharges;
        amtfield.setText(amt + "");
        gdfield.setText(""+guideCharges);
        totalfield.setText(total+"");





        
    }//GEN-LAST:event_calculatebuttonActionPerformed

private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
    System.exit(0);

}//GEN-LAST:event_exitbuttonActionPerformed

private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_pswdActionPerformed

private void daysfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysfieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_daysfieldActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    buttonGroup1.clearSelection();
    DeluxeCar.setSelected(false);
    SDeluxeCar.setSelected(false);
    OrCar.setSelected(false);
    GDradio.setSelected(false);
    daysfield.setText("");
    amtfield.setText("");
    gdfield.setText("");
    totalfield.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABC_Car_Rentals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DeluxeCar;
    private javax.swing.JCheckBox GDradio;
    private javax.swing.JButton OK;
    private javax.swing.JRadioButton OrCar;
    private javax.swing.JRadioButton SDeluxeCar;
    private javax.swing.JTextField amtfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculatebutton;
    private javax.swing.JFrame dashboard;
    private javax.swing.JTextField daysfield;
    private javax.swing.JButton exitbutton;
    private javax.swing.JTextField gdfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JTextField totalfield;
    // End of variables declaration//GEN-END:variables

}
