import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * todo.java
 *
 * Created on 3 Jul, 2020, 12:43:57 PM
 */

/**
 *
 * @author mihir
 */
public class todo extends javax.swing.JFrame {

    Connection con=null;
    Statement stmt = null;
    ResultSet rs = null;
    DefaultTableModel tm = null;
    String currentUserID = null;
    int selectedTaskID;

    /** Creates new form todo */
    public todo() {
        initComponents();
    }

    private void fillShowtask() {

        sTaskTF.setEditable(false);
        sDescTF.setEditable(false);
        sPriorityTF.setEditable(false);
        sStatusCheckbox.setEnabled(false);
        
        buttonGroup2.clearSelection();
        highRadioButton1.setSelected(false);
        mediumRadioButton1.setSelected(false);
        lowRadioButton1.setSelected(false);
        
        int taskid = (Integer)jTable1.getValueAt(jTable1.getSelectedRow(), 4);
        selectedTaskID=taskid;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb", "root", "qwerty");
            stmt = con.createStatement();
            String sql = "Select Task,Description,priority,status from tasks where taskid="+taskid+";";
            rs = stmt.executeQuery(sql);
            rs.first();
            sTaskTF.setText(rs.getString("Task"));
            sDescTF.setText(rs.getString("Description"));
            sPriorityTF.setText(rs.getString("priority"));
            sStatusCheckbox.setSelected(rs.getBoolean("Status"));

            editTaskTF.setText(rs.getString("Task"));
            editDescTF.setText(rs.getString("Description"));
            editStatusCheckbox.setSelected(rs.getBoolean("status"));
            String prior=rs.getString("priority");
            if(prior.equalsIgnoreCase("high"))
            {
                highRadioButton1.setSelected(true);
            }
            else if(prior.equalsIgnoreCase("medium"))
            {
                mediumRadioButton1.setSelected(true);
            }
            else if(prior.equalsIgnoreCase("low"))
            {
                lowRadioButton1.setSelected(true);
            }

            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpFrame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signUpBack = new javax.swing.JButton();
        createAcc = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PF1 = new javax.swing.JPasswordField();
        userIDTF1 = new javax.swing.JTextField();
        userNameTF1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        loginFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PF2 = new javax.swing.JPasswordField();
        userIDTF2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        loginBack = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dashboard = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        addTask = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        addTaskFrame = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        saveNewTask = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        newTaskBack = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        taskTF = new javax.swing.JTextField();
        highRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        lowRadioButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTF = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        showTaskFrame = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        sPriorityTF = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        sDescTF = new javax.swing.JTextArea();
        sTaskTF = new javax.swing.JTextField();
        sStatusCheckbox = new javax.swing.JCheckBox();
        editTaskButton = new javax.swing.JButton();
        deleteTask = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        editTaskFrame = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        highRadioButton1 = new javax.swing.JRadioButton();
        mediumRadioButton1 = new javax.swing.JRadioButton();
        lowRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        editDescTF = new javax.swing.JTextArea();
        editTaskTF = new javax.swing.JTextField();
        editStatusCheckbox = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signUp = new javax.swing.JButton();
        signIn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        signUpFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        signUpFrame.setTitle("User Sign Up");
        signUpFrame.setBounds(new java.awt.Rectangle(600, 400, 600, 400));
        signUpFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signUpFrame.setMinimumSize(new java.awt.Dimension(600, 400));
        signUpFrame.setResizable(false);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel1.setText("Sign Up into To Do List");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 20, 290, 22);

        signUpBack.setText("Back");
        signUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBackActionPerformed(evt);
            }
        });
        jPanel2.add(signUpBack);
        signUpBack.setBounds(500, 10, 80, 25);

        createAcc.setText("Create Account");
        createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccActionPerformed(evt);
            }
        });
        jPanel2.add(createAcc);
        createAcc.setBounds(230, 280, 140, 25);

        jLabel14.setText("Already have Account Click here to Login.");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel14);
        jLabel14.setBounds(180, 320, 236, 16);

        jLabel2.setText("User Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 80, 68, 16);

        jLabel3.setText("User ID:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 140, 47, 16);

        jLabel4.setText("Password:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 200, 70, 16);

        PF1.setToolTipText("");
        PF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF1ActionPerformed(evt);
            }
        });
        jPanel2.add(PF1);
        PF1.setBounds(230, 200, 238, 22);

        userIDTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDTF1ActionPerformed(evt);
            }
        });
        jPanel2.add(userIDTF1);
        userIDTF1.setBounds(230, 140, 238, 22);

        userNameTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTF1ActionPerformed(evt);
            }
        });
        jPanel2.add(userNameTF1);
        userNameTF1.setBounds(230, 80, 238, 22);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout signUpFrameLayout = new javax.swing.GroupLayout(signUpFrame.getContentPane());
        signUpFrame.getContentPane().setLayout(signUpFrameLayout);
        signUpFrameLayout.setHorizontalGroup(
            signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        signUpFrameLayout.setVerticalGroup(
            signUpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        loginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginFrame.setTitle("User Login");
        loginFrame.setBounds(new java.awt.Rectangle(600, 400, 600, 400));
        loginFrame.setMinimumSize(new java.awt.Dimension(600, 400));
        loginFrame.setResizable(false);

        jPanel3.setLayout(null);

        jLabel11.setText("Enter Password:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(120, 180, 94, 16);

        jLabel10.setText("Enter User ID:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(130, 120, 81, 16);

        PF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF2ActionPerformed(evt);
            }
        });
        jPanel3.add(PF2);
        PF2.setBounds(240, 180, 211, 22);

        userIDTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDTF2ActionPerformed(evt);
            }
        });
        jPanel3.add(userIDTF2);
        userIDTF2.setBounds(240, 120, 211, 22);

        jLabel9.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel9.setText("Login Here !!");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(220, 20, 148, 22);

        loginBack.setText("Back");
        loginBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBackActionPerformed(evt);
            }
        });
        jPanel3.add(loginBack);
        loginBack.setBounds(490, 10, 90, 25);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginButton);
        loginButton.setBounds(260, 250, 108, 25);

        jLabel13.setText("Don't have Account Click here to create.");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });
        jPanel3.add(jLabel13);
        jLabel13.setBounds(200, 290, 228, 16);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        dashboard.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        dashboard.setTitle("Dashboard");
        dashboard.setBounds(new java.awt.Rectangle(600, 400, 600, 400));
        dashboard.setMinimumSize(new java.awt.Dimension(600, 400));
        dashboard.setResizable(false);
        dashboard.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dashboardWindowOpened(evt);
            }
        });

        jPanel4.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel4.setLayout(null);

        addTask.setText("Add Task");
        addTask.setToolTipText(" Click to Add new Task");
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });
        jPanel4.add(addTask);
        addTask.setBounds(0, 330, 600, 30);

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Arial Black", 0, 15));
        jTable1.setForeground(new java.awt.Color(51, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task", "Status", "Priority", "Date ", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Click to Edit Task");
        jTable1.setSelectionForeground(new java.awt.Color(153, 102, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(4).setMinWidth(0);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(0);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 600, 271);

        jLabel12.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoApp.png"))); // NOI18N
        jLabel12.setText("To Do List DashboARD");
        jLabel12.setToolTipText(" Dashboard");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(130, 10, 320, 40);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutIcon.png"))); // NOI18N
        logout.setText("Logout");
        logout.setToolTipText("Logout from this Account");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel4.add(logout);
        logout.setBounds(480, 10, 104, 30);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jLabel32.setText("jLabel32");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard.getContentPane());
        dashboard.getContentPane().setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        addTaskFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addTaskFrame.setTitle(" Add Task");
        addTaskFrame.setBounds(new java.awt.Rectangle(600, 400, 600, 400));
        addTaskFrame.setMinimumSize(new java.awt.Dimension(600, 400));
        addTaskFrame.setResizable(false);

        jPanel5.setLayout(null);

        saveNewTask.setText("Save");
        saveNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewTaskActionPerformed(evt);
            }
        });
        jPanel5.add(saveNewTask);
        saveNewTask.setBounds(250, 320, 105, 25);

        jLabel15.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel15.setText(" New Task");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(220, 20, 119, 22);

        newTaskBack.setText("Back");
        newTaskBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTaskBackActionPerformed(evt);
            }
        });
        jPanel5.add(newTaskBack);
        newTaskBack.setBounds(500, 10, 83, 25);

        jLabel19.setText("Task : ");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(130, 100, 40, 16);

        jLabel20.setText("Description : ");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(100, 200, 76, 16);

        jLabel21.setText("Priority : ");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(120, 260, 53, 16);
        jPanel5.add(taskTF);
        taskTF.setBounds(200, 90, 246, 22);

        buttonGroup1.add(highRadioButton);
        highRadioButton.setText("High");
        highRadioButton.setToolTipText("set Priority High");
        jPanel5.add(highRadioButton);
        highRadioButton.setBounds(200, 260, 53, 25);

        buttonGroup1.add(mediumRadioButton);
        mediumRadioButton.setText("Medium");
        jPanel5.add(mediumRadioButton);
        mediumRadioButton.setBounds(290, 260, 73, 25);

        buttonGroup1.add(lowRadioButton);
        lowRadioButton.setText("Low");
        jPanel5.add(lowRadioButton);
        lowRadioButton.setBounds(400, 260, 51, 25);

        descTF.setColumns(20);
        descTF.setRows(5);
        jScrollPane2.setViewportView(descTF);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(200, 120, 246, 96);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jLabel33.setText("jLabel33");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout addTaskFrameLayout = new javax.swing.GroupLayout(addTaskFrame.getContentPane());
        addTaskFrame.getContentPane().setLayout(addTaskFrameLayout);
        addTaskFrameLayout.setHorizontalGroup(
            addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        addTaskFrameLayout.setVerticalGroup(
            addTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        showTaskFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        showTaskFrame.setTitle(" Show Task");
        showTaskFrame.setBounds(new java.awt.Rectangle(600, 400, 600, 400));
        showTaskFrame.setMinimumSize(new java.awt.Dimension(600, 400));
        showTaskFrame.setResizable(false);
        showTaskFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                showTaskFrameWindowActivated(evt);
            }
        });

        jPanel6.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel26.setText("Task");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(280, 20, 56, 22);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(490, 10, 95, 25);

        jLabel30.setText("Status : ");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(140, 250, 49, 16);

        jLabel29.setText("Priority : ");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(140, 200, 53, 16);

        jLabel27.setText("Task : ");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(150, 50, 40, 16);

        jLabel28.setText("Description : ");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(110, 160, 76, 16);
        jPanel6.add(sPriorityTF);
        sPriorityTF.setBounds(210, 200, 254, 22);

        sDescTF.setColumns(20);
        sDescTF.setRows(5);
        jScrollPane4.setViewportView(sDescTF);

        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(210, 80, 254, 96);
        jPanel6.add(sTaskTF);
        sTaskTF.setBounds(210, 50, 254, 22);

        sStatusCheckbox.setText("Done");
        jPanel6.add(sStatusCheckbox);
        sStatusCheckbox.setBounds(210, 240, 57, 25);

        editTaskButton.setText("Edit Task");
        editTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskButtonActionPerformed(evt);
            }
        });
        jPanel6.add(editTaskButton);
        editTaskButton.setBounds(130, 310, 124, 25);

        deleteTask.setText(" Delete Task ");
        deleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskActionPerformed(evt);
            }
        });
        jPanel6.add(deleteTask);
        deleteTask.setBounds(350, 310, 121, 25);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jLabel34.setText("jLabel34");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(0, 0, 610, 400);

        javax.swing.GroupLayout showTaskFrameLayout = new javax.swing.GroupLayout(showTaskFrame.getContentPane());
        showTaskFrame.getContentPane().setLayout(showTaskFrameLayout);
        showTaskFrameLayout.setHorizontalGroup(
            showTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        showTaskFrameLayout.setVerticalGroup(
            showTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        editTaskFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        editTaskFrame.setTitle("Edit Task");
        editTaskFrame.setBounds(new java.awt.Rectangle(600, 400, 600, 40));
        editTaskFrame.setMinimumSize(new java.awt.Dimension(600, 400));
        editTaskFrame.setResizable(false);

        jPanel7.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel22.setText("Edit Task");
        jPanel7.add(jLabel22);
        jLabel22.setBounds(240, 20, 113, 22);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(490, 10, 90, 25);

        jLabel23.setText("Task : ");
        jPanel7.add(jLabel23);
        jLabel23.setBounds(150, 60, 40, 16);

        jLabel24.setText("Description : ");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(110, 170, 76, 16);

        jLabel25.setText("Priority : ");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(130, 230, 53, 16);

        jLabel31.setText("Status : ");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(140, 270, 49, 16);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel7.add(saveButton);
        saveButton.setBounds(240, 310, 105, 25);

        buttonGroup2.add(highRadioButton1);
        highRadioButton1.setText("High");
        highRadioButton1.setToolTipText("set Priority High");
        jPanel7.add(highRadioButton1);
        highRadioButton1.setBounds(200, 220, 53, 25);

        buttonGroup2.add(mediumRadioButton1);
        mediumRadioButton1.setText("Medium");
        jPanel7.add(mediumRadioButton1);
        mediumRadioButton1.setBounds(290, 220, 73, 25);

        buttonGroup2.add(lowRadioButton1);
        lowRadioButton1.setText("Low");
        jPanel7.add(lowRadioButton1);
        lowRadioButton1.setBounds(400, 220, 51, 25);

        editDescTF.setColumns(20);
        editDescTF.setRows(5);
        jScrollPane3.setViewportView(editDescTF);

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(200, 90, 248, 96);
        jPanel7.add(editTaskTF);
        editTaskTF.setBounds(200, 60, 248, 22);

        editStatusCheckbox.setText("Done");
        jPanel7.add(editStatusCheckbox);
        editStatusCheckbox.setBounds(200, 260, 57, 25);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jLabel35.setText("jLabel35");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout editTaskFrameLayout = new javax.swing.GroupLayout(editTaskFrame.getContentPane());
        editTaskFrame.getContentPane().setLayout(editTaskFrameLayout);
        editTaskFrameLayout.setHorizontalGroup(
            editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        editTaskFrameLayout.setVerticalGroup(
            editTaskFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("To-Do List");
        setBounds(new java.awt.Rectangle(600, 400, 600, 400));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel8.setText("To Do List");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 40, 123, 22);

        jLabel6.setText("Create new Account.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 230, 119, 16);

        signUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signUpIcon.png"))); // NOI18N
        signUp.setText("Sign Up");
        signUp.setFocusable(false);
        signUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signUp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        jPanel1.add(signUp);
        signUp.setBounds(110, 170, 134, 50);

        signIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginIcon.png"))); // NOI18N
        signIn.setText("Sign In");
        signIn.setFocusable(false);
        signIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        jPanel1.add(signIn);
        signIn.setBounds(370, 170, 130, 50);

        jLabel7.setText("Login here.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 230, 64, 16);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitIcon.png"))); // NOI18N
        exit.setText("Exit App");
        exit.setFocusable(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(490, 10, 100, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoApp.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 30, 50, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTable() {
        tm.setRowCount(0);
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb", "root", "qwerty");
            stmt = con.createStatement();
            String sql = "Select Task,status,p.priority,DOC,taskid from tasks t inner join priority p on t.priority = p.priority where userid='"+currentUserID+"' order by p.priorityid;";

            rs = stmt.executeQuery(sql);
            if(rs!=null)
            {
                while(rs.next())
                {
                    tm.addRow(new Object [] {rs.getString("Task"), rs.getBoolean("status"), rs.getString("priority"),rs.getDate("DOC"),rs.getInt("TaskID")});
                }
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        //Clearing all Fields on the frame on opening
        userNameTF1.setText(null);
        userIDTF1.setText(null);
        PF1.setText(null);
        this.dispose();
        signUpFrame.setVisible(true);
        userNameTF1.requestFocus();
}//GEN-LAST:event_signUpActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        //Clearing all Fields on the frame on opening
        userIDTF2.setText(null);
        PF2.setText(null);
        this.dispose();
        loginFrame.setVisible(true);
        userIDTF2.requestFocus();
}//GEN-LAST:event_signInActionPerformed

    private void createAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccActionPerformed

        if(userNameTF1.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter the User Name");
            userNameTF1.requestFocus();
        }
        else if(userNameTF1.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter the User Name");
            userNameTF1.requestFocus();
        }
        else if(PF1.getPassword().toString().equals("")||PF1.getPassword().toString().equals(null))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Password");
            PF1.requestFocus();
            return;
        }

        String name=userNameTF1.getText();
        String uid=userIDTF1.getText();
        String pass = new String(PF1.getPassword());
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb","root","qwerty");
            stmt = con.createStatement();
            String sql="INSERT INTO User(UserID, Name, DOJ, Password) VALUES ('"+uid+"', '"+ name +"', curdate(), '"+pass+"');";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane,"Congrats! Account created Successfully");

            signUpFrame.dispose();
            this.setVisible(true);

            stmt.close();
            con.close();
        }
        catch(SQLIntegrityConstraintViolationException e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
            userIDTF1.setText(null);
            userIDTF1.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            return;
        }
}//GEN-LAST:event_createAccActionPerformed

    private void PF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF1ActionPerformed

       createAccActionPerformed(evt);
       /* if(PF1.getPassword().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please Enter Password");
            PF1.requestFocus();
        }
        String name=userNameTF1.getText();
        String uid=userIDTF1.getText();
        String pass = new String(PF1.getPassword());
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb","root","qwerty");
            stmt = con.createStatement();
            String sql="INSERT INTO User(UserID, Name, DOJ, Password) VALUES ('"+name+"', '"+ uid +"', curdate(), '"+pass+"');";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane,"Congrats! Account created Successfully");

            signUpFrame.dispose();
            this.setVisible(true);

            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }*/
    }//GEN-LAST:event_PF1ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String uid=userIDTF2.getText();
        String pwd=new String(PF2.getPassword());
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb","root","qwerty");
            stmt = con.createStatement();
            String sql="Select password,UserID from User where UserID='"+uid+"';";
            rs = stmt.executeQuery(sql);
            rs.first();
            String pass = rs.getString("password");
            if(pwd.equals(pass))
            {
                currentUserID=rs.getString("UserID");
                loginFrame.dispose();

                dashboard.setVisible(true);
                addTask.requestFocus();
                JOptionPane.showMessageDialog(null,"Login Successfully.\nWelcome "+currentUserID+".");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"See, your userID or password is wrong.\nTry again!");
            }
            rs.close();
            con.close();
            stmt.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        refreshTable();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        tm.setRowCount(0);
        currentUserID = null;
        dashboard.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
        loginFrame.dispose();
        signUpFrame.setVisible(true);
        userNameTF1.requestFocus();
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
        signUpFrame.dispose();
        loginFrame.setVisible(true);
        userIDTF2.requestFocus();
    }//GEN-LAST:event_jLabel14MouseReleased

    private void loginBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBackActionPerformed
        //Clearing all Fields on the frame on opening
        userIDTF2.setText(null);
        PF2.setText(null);
        loginFrame.dispose();
        this.setVisible(true);    
    }//GEN-LAST:event_loginBackActionPerformed

    private void signUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBackActionPerformed
        //Clearing all Fields on the frame on opening
        userNameTF1.setText(null);
        userIDTF1.setText(null);
        PF1.setText(null);
        signUpFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_signUpBackActionPerformed

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed
        dashboard.dispose();
        addTaskFrame.setVisible(true);
}//GEN-LAST:event_addTaskActionPerformed

    private void newTaskBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTaskBackActionPerformed
        taskTF.setText(null);
        descTF.setText(null);
        buttonGroup1.clearSelection();
        highRadioButton.setSelected(false);
        mediumRadioButton.setSelected(false);
        lowRadioButton.setSelected(false);
        addTaskFrame.dispose();
        dashboard.setVisible(true);
        addTask.requestFocus();
        refreshTable();
    }//GEN-LAST:event_newTaskBackActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
}//GEN-LAST:event_exitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        editTaskFrame.dispose();
        showTaskFrame.setVisible(true);
        fillShowtask();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskButtonActionPerformed
        showTaskFrame.dispose();
        editTaskFrame.setVisible(true);
}//GEN-LAST:event_editTaskButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        showTaskFrame.dispose();
        refreshTable();
        dashboard.setVisible(true);
        addTask.requestFocus();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void saveNewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewTaskActionPerformed
        String task = taskTF.getText();
        String desc = descTF.getText();
        String priority=null;
        if(task.equals("")||task.equals(null))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter the task details");
            taskTF.requestFocus();
            return;
        }
        if(highRadioButton.isSelected())
        {
            priority="High";
        }else if(mediumRadioButton.isSelected())
        {
            priority="Medium";
        }else if(lowRadioButton.isSelected())
        {
            priority="Low";
        }else
        {
            JOptionPane.showMessageDialog(rootPane,"Set your priority");
            highRadioButton.requestFocus();
            return;
        }

        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb","root","qwerty");
            stmt = con.createStatement();
            String sql="Insert into tasks values('"+currentUserID+"','"+task+"','"+desc+"','"+priority+"',false,curdate(),null);";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane,"Task : "+task+"\nSuccessfully added ^_^");

            taskTF.setText(null);
            descTF.setText(null);
            highRadioButton.setSelected(false);
            mediumRadioButton.setSelected(false);
            lowRadioButton.setSelected(false);
            buttonGroup1.clearSelection();

            addTaskFrame.dispose();
            dashboard.setVisible(true);
            addTask.requestFocus();

            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
        refreshTable();
}//GEN-LAST:event_saveNewTaskActionPerformed

    private void dashboardWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dashboardWindowOpened
        tm = (DefaultTableModel)jTable1.getModel();
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        jTable1.getTableHeader().setBackground(new Color(233,97,102));
        refreshTable();
    }//GEN-LAST:event_dashboardWindowOpened

    private void showTaskFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_showTaskFrameWindowActivated

    }//GEN-LAST:event_showTaskFrameWindowActivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        dashboard.dispose();
        showTaskFrame.setVisible(true);
        fillShowtask();
    }//GEN-LAST:event_jTable1MouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        editTaskFrame.dispose();
        showTaskFrame.setVisible(true);
        String task=editTaskTF.getText();
        String desc=editDescTF.getText();
        String priority=null;
        if(task.equals("")||task.equals(null))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter the task details");
            taskTF.requestFocus();
            return;
        }
        if(highRadioButton1.isSelected())
        {
            priority="High";
        }else if(mediumRadioButton1.isSelected())
        {
            priority="Medium";
        }else if(lowRadioButton1.isSelected())
        {
            priority="Low";
        }else
        {
            JOptionPane.showMessageDialog(rootPane,"Set your priority");
            highRadioButton1.requestFocus();
            return;
        }
        Boolean status = editStatusCheckbox.isSelected();

        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb","root","qwerty");
            stmt = con.createStatement();
            String sql="update tasks\nset priority='"+priority+"',description='"+desc+"',task='"+task+"',status="+status+"\nwhere taskid="+selectedTaskID+";";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane,"Task : "+task+"\nSuccessfully Saved ^_^");

            editTaskFrame.dispose();
            fillShowtask();
            showTaskFrame.setVisible(true);

            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskActionPerformed
        String task=sTaskTF.getText();
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tododb","root","qwerty");
            stmt = con.createStatement();
            String sql="delete from tasks where taskID="+selectedTaskID+";";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane,"Task : "+task+"\nTask Deleted ^_^");

            showTaskFrame.dispose();
            refreshTable();
            dashboard.setVisible(true);
            addTask.requestFocus();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
}//GEN-LAST:event_deleteTaskActionPerformed

    private void userNameTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTF1ActionPerformed
        if(userNameTF1.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter the User Name");
            userNameTF1.requestFocus();
        }
        else
        {
            userIDTF1.requestFocus();
        }
    }//GEN-LAST:event_userNameTF1ActionPerformed

    private void userIDTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDTF1ActionPerformed

        if(userIDTF1.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter the User ID");
            userIDTF1.requestFocus();
        }
        else
        {
            PF1.requestFocus();
        }
    }//GEN-LAST:event_userIDTF1ActionPerformed

    private void userIDTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDTF2ActionPerformed
        if(userIDTF2.getText().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "UserID is required");
        }
        else
        {
            PF2.requestFocus();
        }
    }//GEN-LAST:event_userIDTF2ActionPerformed

    private void PF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF2ActionPerformed
        loginButtonActionPerformed(evt);
    }//GEN-LAST:event_PF2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new todo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PF1;
    private javax.swing.JPasswordField PF2;
    private javax.swing.JButton addTask;
    private javax.swing.JFrame addTaskFrame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createAcc;
    private javax.swing.JFrame dashboard;
    private javax.swing.JButton deleteTask;
    private javax.swing.JTextArea descTF;
    private javax.swing.JTextArea editDescTF;
    private javax.swing.JCheckBox editStatusCheckbox;
    private javax.swing.JButton editTaskButton;
    private javax.swing.JFrame editTaskFrame;
    private javax.swing.JTextField editTaskTF;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton highRadioButton;
    private javax.swing.JRadioButton highRadioButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginBack;
    private javax.swing.JButton loginButton;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton lowRadioButton;
    private javax.swing.JRadioButton lowRadioButton1;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JRadioButton mediumRadioButton1;
    private javax.swing.JButton newTaskBack;
    private javax.swing.JTextArea sDescTF;
    private javax.swing.JTextField sPriorityTF;
    private javax.swing.JCheckBox sStatusCheckbox;
    private javax.swing.JTextField sTaskTF;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveNewTask;
    private javax.swing.JFrame showTaskFrame;
    private javax.swing.JButton signIn;
    private javax.swing.JButton signUp;
    private javax.swing.JButton signUpBack;
    private javax.swing.JFrame signUpFrame;
    private javax.swing.JTextField taskTF;
    private javax.swing.JTextField userIDTF1;
    private javax.swing.JTextField userIDTF2;
    private javax.swing.JTextField userNameTF1;
    // End of variables declaration//GEN-END:variables

}
