/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dashboard.java
 *
 * Created on Jul 16, 2020, 5:20:13 PM
 */

/**
 *
 * @author nkant
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Dashboard extends javax.swing.JFrame {
    String date,District,state,CVT,c_name,choice;
    int sno;
    int i=0;
    int[] ab = new int[9];
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;

    /** Creates new form Dashboard */
    public Dashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginframe = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        placeframe = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statebox = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        districtbox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cvtbox = new javax.swing.JComboBox();
        placeformentry = new javax.swing.JButton();
        imp1 = new javax.swing.JLabel();
        imp2 = new javax.swing.JLabel();
        imp4 = new javax.swing.JLabel();
        BiodataFrame = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        HEQbox = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        occu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        mb = new javax.swing.JTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        Back = new javax.swing.JButton();
        NextEnrty = new javax.swing.JButton();
        sno_box = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        Finish = new javax.swing.JButton();
        agefield = new javax.swing.JTextField();
        datefield = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Analysis = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pop = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ratio = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        emp = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lit = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        CHoiceanalysis = new javax.swing.JFrame();
        overall = new javax.swing.JButton();
        statechanal = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        loginframe.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginframeLayout = new javax.swing.GroupLayout(loginframe.getContentPane());
        loginframe.getContentPane().setLayout(loginframeLayout);
        loginframeLayout.setHorizontalGroup(
            loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginframeLayout.createSequentialGroup()
                .addGroup(loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginframeLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password, 0, 0, Short.MAX_VALUE)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addGroup(loginframeLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(login)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        loginframeLayout.setVerticalGroup(
            loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginframeLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(login)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        placeframe.setMinimumSize(new java.awt.Dimension(600, 400));
        placeframe.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                placeframeWindowActivated(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 24));
        jLabel4.setText("Place");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel5.setText("State:");

        statebox.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Andhra Pradesh (AP)", "Arunachal Pradesh (AR)", "Assam (AS)", "Bihar (BR)", "Chhattisgarh (CG)", "Goa (GA)", "Gujarat (GJ)", "Haryana (HR)", "Himachal Pradesh (HP)", "Jharkhand (JH)", "Karnataka (KA)", "Kerala (KL)", "Madhya Pradesh (MP)", "Maharashtra (MH)", "Manipur (MN)", "Meghalaya (ML)", "Mizoram (MZ)", "Nagaland (NL)", "Odisha(OR)", "Punjab (PB)", "Rajasthan (RJ)", "Sikkim (SK)", "Tamil Nadu (TN)", "Telangana (TS)", "Tripura (TR)", "Uttar Pradesh (UP)", "Uttarakhand (UK)", "West Bengal (WB)", "Union Territories(UT)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        statebox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateboxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(statebox);

        jLabel6.setText("District:");

        districtbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        districtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtboxActionPerformed(evt);
            }
        });
        districtbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                districtboxFocusGained(evt);
            }
        });

        jLabel7.setText("City/Village/Town:");

        cvtbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cvtbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cvtboxFocusGained(evt);
            }
        });

        placeformentry.setText("Next");
        placeformentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeformentryActionPerformed(evt);
            }
        });

        imp1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        imp1.setForeground(new java.awt.Color(255, 0, 0));
        imp1.setText(" ");

        imp2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        imp2.setForeground(new java.awt.Color(255, 51, 51));
        imp2.setText(" ");

        imp4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imp4.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout placeframeLayout = new javax.swing.GroupLayout(placeframe.getContentPane());
        placeframe.getContentPane().setLayout(placeframeLayout);
        placeframeLayout.setHorizontalGroup(
            placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeframeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeframeLayout.createSequentialGroup()
                        .addComponent(imp4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel4))
                    .addGroup(placeframeLayout.createSequentialGroup()
                        .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, placeframeLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(placeformentry)
                                .addGap(15, 15, 15))
                            .addGroup(placeframeLayout.createSequentialGroup()
                                .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imp2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imp1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cvtbox, 0, 84, Short.MAX_VALUE)
                                    .addComponent(districtbox, 0, 84, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        placeframeLayout.setVerticalGroup(
            placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeframeLayout.createSequentialGroup()
                .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeframeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imp4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(placeframeLayout.createSequentialGroup()
                        .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(districtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imp1))
                        .addGap(53, 53, 53)
                        .addGroup(placeframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cvtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imp2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(placeformentry))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        BiodataFrame.setMinimumSize(new java.awt.Dimension(734, 434));
        BiodataFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                BiodataFrameWindowActivated(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel9.setText("Biodata");

        jLabel10.setText("S.No. :");

        jLabel11.setText("Name :");

        jLabel12.setText("Date of Birth :");

        jLabel13.setText("Age:");
        jLabel13.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel13MouseWheelMoved(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setText("Gender : ");

        jLabel15.setText("Disability :");

        jRadioButton1.setText("Yes");
        jRadioButton1.setActionCommand(jRadioButton1.getText());
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("jRadioButton2");

        jLabel16.setText("Literacy :");

        jRadioButton3.setText("Literate");
        jRadioButton3.setActionCommand(jRadioButton3.getText());
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Illiterate ");
        jRadioButton4.setActionCommand(jRadioButton4.getText());

        jLabel17.setText("Educational Qualification: ");

        HEQbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("Employment Status: ");

        jRadioButton5.setText("Employed");
        jRadioButton5.setActionCommand(jRadioButton5.getText());
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Unemployed ");
        jRadioButton6.setActionCommand(jRadioButton6.getText());

        jLabel19.setText("Occupation:");

        jLabel20.setText("Income:");

        jLabel21.setText("Mobile:");

        jRadioButton7.setText("Male");
        jRadioButton7.setActionCommand(jRadioButton7.getText());
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setText("Female");
        jRadioButton8.setActionCommand( jRadioButton8.getText() );
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("Other");
        jRadioButton9.setActionCommand( jRadioButton9.getText() );

        jRadioButton10.setText("No");
        jRadioButton10.setActionCommand(jRadioButton10.getText());

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        NextEnrty.setText("Next entry");
        NextEnrty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextEnrtyActionPerformed(evt);
            }
        });

        namefield.setText(" ");

        Finish.setText("Finish");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        agefield.setText(" ");
        agefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agefieldActionPerformed(evt);
            }
        });
        agefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                agefieldFocusGained(evt);
            }
        });

        datefield.setText("YYYY-MM-DD");

        javax.swing.GroupLayout BiodataFrameLayout = new javax.swing.GroupLayout(BiodataFrame.getContentPane());
        BiodataFrame.getContentPane().setLayout(BiodataFrameLayout);
        BiodataFrameLayout.setHorizontalGroup(
            BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiodataFrameLayout.createSequentialGroup()
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BiodataFrameLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sno_box, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BiodataFrameLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(8, 8, 8)
                                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton10))))
                            .addGroup(BiodataFrameLayout.createSequentialGroup()
                                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton5)
                                            .addComponent(jRadioButton6)))
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton4)
                                            .addComponent(jRadioButton3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addComponent(Back)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NextEnrty)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Finish))
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiodataFrameLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(occu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HEQbox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))))
                            .addGroup(BiodataFrameLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton7))
                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BiodataFrameLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addComponent(jRadioButton8)
                                        .addGap(85, 85, 85)
                                        .addComponent(jRadioButton9))
                                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(236, 236, 236))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BiodataFrameLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namefield, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))))
                    .addGroup(BiodataFrameLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BiodataFrameLayout.setVerticalGroup(
            BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiodataFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sno_box, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton3)
                    .addComponent(HEQbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel19)
                    .addComponent(occu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addGap(26, 26, 26)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(BiodataFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextEnrty)
                    .addComponent(Finish)
                    .addComponent(Back))
                .addContainerGap())
        );

        Analysis.setMinimumSize(new java.awt.Dimension(450, 350));
        Analysis.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                AnalysisWindowActivated(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Population:");

        pop.setText("jLabel22");

        jLabel22.setText("Sex Ratio:");

        ratio.setText("jLabel23");

        jLabel23.setText("Independents:");

        dep.setText("jLabel24");

        jLabel26.setText("Employed:");

        emp.setText("jLabel27");

        jLabel25.setText("Literacy:");

        lit.setText("Disabled");

        jLabel27.setText("Disabled:");

        dis.setText("jLabel28");

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnalysisLayout = new javax.swing.GroupLayout(Analysis.getContentPane());
        Analysis.getContentPane().setLayout(AnalysisLayout);
        AnalysisLayout.setHorizontalGroup(
            AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pop)
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(AnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dep)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(AnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(AnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(lit)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(AnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratio)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(AnalysisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dis)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnalysisLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(2, 2, 2)
                .addComponent(jButton6)
                .addContainerGap())
        );
        AnalysisLayout.setVerticalGroup(
            AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnalysisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pop))
                .addGap(31, 31, 31)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(dep))
                .addGap(26, 26, 26)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(emp))
                .addGap(26, 26, 26)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lit))
                .addGap(26, 26, 26)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(dis))
                .addGap(34, 34, 34)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ratio))
                .addGap(9, 9, 9)
                .addGroup(AnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        CHoiceanalysis.setMinimumSize(new java.awt.Dimension(400, 300));

        overall.setText("Overall");
        overall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallActionPerformed(evt);
            }
        });

        statechanal.setText(" State");
        statechanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statechanalActionPerformed(evt);
            }
        });

        jButton3.setText("District");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText(" Town/City/Village");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CHoiceanalysisLayout = new javax.swing.GroupLayout(CHoiceanalysis.getContentPane());
        CHoiceanalysis.getContentPane().setLayout(CHoiceanalysisLayout);
        CHoiceanalysisLayout.setHorizontalGroup(
            CHoiceanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHoiceanalysisLayout.createSequentialGroup()
                .addGroup(CHoiceanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CHoiceanalysisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(overall, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statechanal, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(CHoiceanalysisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(CHoiceanalysisLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton7)))
                .addContainerGap())
        );
        CHoiceanalysisLayout.setVerticalGroup(
            CHoiceanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHoiceanalysisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CHoiceanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overall)
                    .addComponent(statechanal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CHoiceanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(33, 33, 33)
                .addComponent(jButton7)
                .addGap(145, 145, 145))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 36));
        jLabel1.setText("Census of India 2021");

        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Analysis");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    this.dispose();
    loginframe.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
String User = username.getText();
String pwd = new String(password.getPassword());
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT Password FROM enumerator WHERE Username = '" + User + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
    String pass = rs.getString("password");
    if(pwd.equals(pass)){
        loginframe.dispose();
        placeframe.setVisible(true);
    }
    else{
    JOptionPane.showMessageDialog(null, "Incorrect username or password. Try again!");
    }
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
}//GEN-LAST:event_loginActionPerformed

    private void placeframeWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_placeframeWindowActivated
        // TODO add your handling code here:
//districtbox.setEnabled(false);

cvtbox.removeAllItems();
districtbox.removeAllItems();
districtbox.addItem("--Select district--");
cvtbox.removeAllItems();
cvtbox.addItem("--Select City/Town/Village--");
districtbox.setSelectedItem("--Select college--");
cvtbox.setSelectedItem("--Select City/Town/Village--");
if(c_name.equals("State")){
    statebox.setEnabled(true);
    districtbox.setEnabled(false);
    cvtbox.setEnabled(false);
}
else if(c_name.equals("District")){
    districtbox.setEnabled(true);
    cvtbox.setEnabled(false);
    statebox.setEnabled(false);
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT district FROM biodata where district is not null ORDER BY district ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    districtbox.addItem(rs.getString("district"));
    }
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
}
else if(c_name.equals("Town_City_Village")){
    cvtbox.setEnabled(true);
    districtbox.setEnabled(false);
    statebox.setEnabled(false);
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT Town_City_Village FROM biodata where Town_City_Village is not null ORDER BY Town_City_Village ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    districtbox.addItem(rs.getString("Town_City_Village"));
    }
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
}
else{
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT district FROM biodata where district is not null ORDER BY district ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    districtbox.addItem(rs.getString("district"));
    }
    rs.close();
    sql = "SELECT DISTINCT Town_city_village FROM biodata where Town_city_village is not null ORDER BY Town_city_village ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    cvtbox.addItem(rs.getString("Town_city_village"));
    }
    districtbox.setSelectedItem("--Select college--");
    cvtbox.setSelectedItem("--Select City/Town/Village--");
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    }
    }//GEN-LAST:event_placeframeWindowActivated
  
    private void districtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtboxActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_districtboxActionPerformed

    private void placeformentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeformentryActionPerformed
        // TODO add your handling code here:
if(c_name.equals("District")){
    choice = (String)districtbox.getSelectedItem();
    if(districtbox.getSelectedIndex()== 0 || districtbox.getSelectedIndex()==-1){
        choice = JOptionPane.showInputDialog(null, "District not on the list?\nEnter the name of the district here:");}
    if(choice == null || choice.equals("")){
    JOptionPane.showMessageDialog(null, "Please enter the district");
    requestFocusInWindow();}
    placeframe.dispose();
    Analysis.setVisible(true);
}
else if(c_name.equals("State")){
    choice = (String)statebox.getSelectedValue();
    if(choice == null){
    JOptionPane.showMessageDialog(null, "Please enter the state to continue");
    requestFocusInWindow();
}
    placeframe.dispose();
    Analysis.setVisible(true);
}
else if(c_name.equals("Town_City_Village")){
    choice = (String)cvtbox.getSelectedItem();
    if(cvtbox.getSelectedIndex()== 0 || cvtbox.getSelectedIndex()==-1){
        choice = JOptionPane.showInputDialog(null, "Town/City/Village not on the list?\nEnter the name of the Town/City/Village here:");
    }
    if(choice == null || choice.equals("")){
    JOptionPane.showMessageDialog(null, "Please enter the Town/City/Village to continue");
    requestFocusInWindow();
    }
    placeframe.dispose();
    Analysis.setVisible(true);
}
else{
District = (String)districtbox.getSelectedItem();
CVT = (String)cvtbox.getSelectedItem();
state = (String)statebox.getSelectedValue();
    if((districtbox.getSelectedIndex()== 0 || districtbox.getSelectedIndex()==-1)&& districtbox.isEnabled()){
    District = JOptionPane.showInputDialog(null, "District not on the list?\nEnter the name of the district here:");
}
if(cvtbox.getSelectedIndex()==0 || cvtbox.getSelectedIndex()==-1){
    CVT = JOptionPane.showInputDialog(null, "Town/City/Village not on the list?\nEnter the name of the Town/City/Village here:");
}
    if((District == null || District.equals("")||CVT == null || CVT.equals("")||state == null) && districtbox.isEnabled()){
    JOptionPane.showMessageDialog(null, "Please enter the fields marked important");
    imp1.setText("*");
    imp2.setText("*");
    imp4.setText("*");
    return;
    }
    requestFocusInWindow();

try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "INSERT INTO biodata( District, Town_City_Village, State) VALUES('" + District + "', '" + CVT + "', '" + state + "');";
    System.out.println(sql);
    stmt.executeUpdate(sql);
    
    placeframe.dispose();
    BiodataFrame.setVisible(true);
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
}
}//GEN-LAST:event_placeformentryActionPerformed

    private void stateboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateboxMouseClicked
        // TODO add your handling code here:
    
}//GEN-LAST:event_stateboxMouseClicked

    private void BiodataFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_BiodataFrameWindowActivated
        
namefield.setText("");
datefield.setText("YYYY-MM-DD");
agefield.setText("");
buttonGroup1.clearSelection();
buttonGroup1.add(jRadioButton7);
buttonGroup1.add(jRadioButton8);
buttonGroup1.add(jRadioButton9);


buttonGroup2.clearSelection();
buttonGroup2.add(jRadioButton1);
buttonGroup2.add(jRadioButton10);


buttonGroup3.clearSelection();
buttonGroup3.add(jRadioButton3);
buttonGroup3.add(jRadioButton4);


buttonGroup4.clearSelection();
buttonGroup4.add(jRadioButton5);
buttonGroup4.add(jRadioButton6);


HEQbox.removeAllItems();
HEQbox.addItem("--Select level--");
occu.setText("");
in.setText("");
mb.setText("");

    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT count(*) FROM biodata;";
    rs = stmt.executeQuery(sql);
    rs.first();
    //userIDLabel.setText(rs.getString("UserID"));
    sno = rs.getInt(1);
    sno_box.setText("" + sno);
    rs.close();
    sql = "SELECT DISTINCT HEQ FROM biodata where HEQ is not NULL ORDER BY HEQ ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    HEQbox.addItem(rs.getString("HEQ"));
    }
    HEQbox.setSelectedItem("--Select level--");
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_BiodataFrameWindowActivated

 private void entry(){
try{
String name = namefield.getText();
String occupation = occu.getText();
int income = Integer.parseInt(in.getText());
long Mobile = Long.parseLong(mb.getText());
String gender = buttonGroup1.getSelection().getActionCommand();
String disability = buttonGroup2.getSelection().getActionCommand();
String literacy = buttonGroup3.getSelection().getActionCommand();
String employment_status = buttonGroup4.getSelection().getActionCommand();
String edq = (String)HEQbox.getSelectedItem();
if(HEQbox.getSelectedIndex()==0 || HEQbox.getSelectedIndex()==-1){
    edq = JOptionPane.showInputDialog(null, "Level not on the list?\nEnter the level here:");
}
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "update biodata set Name = '" + name + "',Gender = '" + gender + "',Disability = '" + disability + "',literacy_status = '" + literacy + "',HEQ = '" + edq + "',Employment = '" + employment_status + "' ,Occupation = '" + occupation + "' ,Income = " + income + ",Mobile = " + Mobile + " where s_no = " + sno + ";";
    System.out.println(sql);
    stmt.executeUpdate(sql); 
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
} 
    }
    private void NextEnrtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextEnrtyActionPerformed
        // TODO add your handling code here:
        entry();
        JOptionPane.showMessageDialog(rootPane, "Information saved.\n Fill next entry");
        try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "INSERT INTO biodata( District, Town_City_Village, State) VALUES('" + District + "', '" + CVT + "', '" + state + "');";
    System.out.println(sql);
    stmt.executeUpdate(sql);

    placeframe.dispose();
    BiodataFrame.setVisible(true);
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
        BiodataFrame.setVisible(false);
        BiodataFrame.setVisible(true);

}//GEN-LAST:event_NextEnrtyActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
entry();
BiodataFrame.dispose();
placeframe.setVisible(true);
}//GEN-LAST:event_BackActionPerformed

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        // TODO add your handling code here:
        entry();
        System.exit(0);
}//GEN-LAST:event_FinishActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CHoiceanalysis.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Analysis.dispose();

        CHoiceanalysis.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel13MouseWheelMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel13MouseWheelMoved

    private void agefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agefieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_agefieldActionPerformed

    private void agefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agefieldFocusGained
        // TODO add your handling code here:
       agefield.setEditable(false);
        date = datefield.getText();
       if(date.equals("YYYY-MM-DD") || date.equals("")){
           date = JOptionPane.showInputDialog(null, "Please enter the date to continue:");
           datefield.requestFocus();
           datefield.setEditable(false);
           datefield.setText(date);
       }
           try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "update biodata set DOB = '" + date + "' where s_no = " + sno + ";";
    System.out.println(sql);
    stmt.executeUpdate(sql);
    sql = "update biodata set age = floor(DATEDIFF(curdate(),DOB)/365) where s_no = " + sno + ";";
    System.out.println(sql);
    stmt.executeUpdate(sql);
    sql = "select age from biodata where s_no = " + sno + ";";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
    agefield.setText("" + rs.getInt("age"));
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_agefieldFocusGained

    private void districtboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_districtboxFocusGained
        // TODO add your handling code here:
   
 /*   try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT district FROM biodata where state = ' " + state + " ' and district is not null ORDER BY district ASC ;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    districtbox.addItem(rs.getString("district"));
    }
    districtbox.setSelectedItem("----Select District----");
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
    }//GEN-LAST:event_districtboxFocusGained
 catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}*/
    }
        private void cvtboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cvtboxFocusGained
            // TODO add your handling code here:
    /*try{
            District = (String)districtbox.getSelectedItem();
           if(districtbox.getSelectedIndex()== 0 || districtbox.getSelectedIndex()==-1){
    District = JOptionPane.showInputDialog(null, "District not on the list?\nEnter the name of the district here:");
}
    if(District == null || District.equals("")){
    JOptionPane.showMessageDialog(null, "Please enter the district to continue");
    return;
    }
    
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT Town_City_Village FROM biodata where district = ' " + District + " ' and Town_City_Village is not null ORDER BY Town_City_Village ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
    cvtbox.addItem(rs.getString("Town_City_Village"));
    }
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}*/

        }//GEN-LAST:event_cvtboxFocusGained

        private void overallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallActionPerformed
            // TODO add your handling code here:
            c_name = "s_no";
            choice = "s_no";
            CHoiceanalysis.dispose();
            Analysis.setVisible(true);

        }//GEN-LAST:event_overallActionPerformed

        private void statechanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statechanalActionPerformed
            // TODO add your handling code here:
            c_name = "State";
            CHoiceanalysis.dispose();
            placeframe.setVisible(true);
        }//GEN-LAST:event_statechanalActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:
            c_name = "District";
            CHoiceanalysis.dispose();
            placeframe.setVisible(true);
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
            c_name = "Town_City_Village";
            CHoiceanalysis.dispose();
            placeframe.setVisible(true);
        }//GEN-LAST:event_jButton5ActionPerformed
private void perform(String sql)
{
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("count(*)");
    if((i!=0) && (i<5)){
        ab[i]=(100*ab[i])/ab[0];}
    i++;
    requestFocusInWindow();
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
}
        private void AnalysisWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AnalysisWindowActivated
            // TODO add your handling code here:
    //try{
            i=0;
    pop.setText("");
    dep.setText("");
    emp.setText("");
    lit.setText("");
    dis.setText("");
    ratio.setText("");
    perform("select count(*) from biodata where "+c_name+" = '"+choice+"' ;");
    perform("select count(*) from biodata where age between 14 and 64 and "+c_name+" = '"+choice+"';");
    perform("select count(*) from biodata where employment = 'Employed' and "+c_name+" = '"+choice+"' ;");
    perform("select count(*) from biodata where literacy_status = 'Literate' and "+c_name+" = '"+choice+"' ;");
    perform("select count(*) from biodata where disability = 'Yes' and "+c_name+" = '"+choice+"' ;");
    perform("select count(*) from biodata where gender = 'Female' and "+c_name+" = '"+choice+"' ;");
    perform("select count(*) from biodata where gender = 'Male' and "+c_name+" = '"+choice+"' ;");
    /*
    con = DriverManager.getConnection("jdbc:mysql://localhost/census_2021", "root", "nikhita");
    stmt = con.createStatement();
    String sql="select count(*) as pop from biodata  where "+c_name+" = '"+choice+"' ;";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]= rs.getInt("pop");
    System.out.println("after input");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    System.out.println("after if statement");
    i++;
    requestFocusInWindow();
    rs.close();
    
    //second
    sql="select count(*) as pop from biodata where age between 14 and 64 and "+c_name+" = '"+choice+"';";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("pop");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    i++;
    requestFocusInWindow();
    rs.close();
    //thrid
    sql="select count(*) as pop from biodata where employment = 'employed' and "+c_name+" = ' "+choice+"' ;";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("pop");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    i++;
    requestFocusInWindow();
    rs.close();
    //fourth
    sql="select count(*) as pop from biodata where literacy_status = 'literate' and "+c_name+" = '"+choice+"' ;";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("pop");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    i++;
    requestFocusInWindow();
    rs.close();
    //fifth
    sql="select count(*) as pop from biodata where disability = 'Yes' and "+c_name+" = '"+choice+"' ;";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("pop");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    i++;
    requestFocusInWindow();
    rs.close();
    //sixth
    sql="select count(*) as pop from biodata where gender = 'Female' and "+c_name+" = '"+choice+"' ;";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("pop");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    i++;
    requestFocusInWindow();
    rs.close();
    //seventh
    sql="select count(*) as pop from biodata where gender = 'Male' and "+c_name+" = '"+choice+"' ;";
    rs = stmt.executeQuery(sql);
    rs.first();
    ab[i]=rs.getInt("pop");
    if((i!=0) && (i<5)){
        ab[i]=(ab[i]/ab[0])*100;}
    i++;
    requestFocusInWindow();
    rs.close();
    
    stmt.close();
    con.close();
    float ra = (float)ab[6]/(float)ab[5];
    pop.setText("" + ab[0]);
    dep.setText("" + ab[1]);
    emp.setText("" + ab[2]);
    lit.setText("" + ab[3]);
    dis.setText("" + ab[4]);
    ratio.setText("" + ra);

}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}*/
float ra = (float)ab[6]/(float)ab[5];
pop.setText("" + ab[0]);
dep.setText("" + ab[1] +"%");
emp.setText("" + ab[2]+"%");
lit.setText("" + ab[3]+"%");
dis.setText("" + ab[4]+"%");
ratio.setText("" + ra +" : 1 ");
//c_name="";
//choice="";
    
        }//GEN-LAST:event_AnalysisWindowActivated

        private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            // TODO add your handling code here:
            c_name = "";
            choice = "";
        }//GEN-LAST:event_formWindowActivated

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            // TODO add your handling code here:
            Analysis.dispose();
            System.exit(0);
        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            // TODO add your handling code here:
            CHoiceanalysis.dispose();
            this.setVisible(true);
        }//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Analysis;
    private javax.swing.JButton Back;
    private javax.swing.JFrame BiodataFrame;
    private javax.swing.JFrame CHoiceanalysis;
    private javax.swing.JButton Finish;
    private javax.swing.JComboBox HEQbox;
    private javax.swing.JButton NextEnrty;
    private javax.swing.JTextField agefield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox cvtbox;
    private javax.swing.JTextField datefield;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel dis;
    private javax.swing.JComboBox districtbox;
    private javax.swing.JLabel emp;
    private javax.swing.JLabel imp1;
    private javax.swing.JLabel imp2;
    private javax.swing.JLabel imp4;
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lit;
    private javax.swing.JButton login;
    private javax.swing.JFrame loginframe;
    private javax.swing.JTextField mb;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField occu;
    private javax.swing.JButton overall;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton placeformentry;
    private javax.swing.JFrame placeframe;
    private javax.swing.JLabel pop;
    private javax.swing.JLabel ratio;
    private javax.swing.JLabel sno_box;
    private javax.swing.JList statebox;
    private javax.swing.JButton statechanal;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
