import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainframe.java
 *
 * Created on 11 Jul, 2020, 7:07:01 PM
 */

/**
 *
 * @author madhu
 */
public class mainframe extends javax.swing.JFrame {
    Connection con = null;
Statement stmt = null;
ResultSet rs = null;
   DefaultTableModel tm = null;
String currentUserID = null;
String userToView = null;






    /** Creates new form mainframe */
    public mainframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginFrame = new javax.swing.JFrame();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pf1 = new javax.swing.JPasswordField();
        usertf1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Signup_Frame = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametf1 = new javax.swing.JTextField();
        usernametf1 = new javax.swing.JTextField();
        pwdf1 = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        Issue_frame = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        return_frame = new javax.swing.JFrame();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        pay_frame = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        dashboard = new javax.swing.JFrame();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        LoginFrame.setMinimumSize(new java.awt.Dimension(400, 500));

        jButton7.setText("Sign In ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel16.setText("WELCOME");

        javax.swing.GroupLayout LoginFrameLayout = new javax.swing.GroupLayout(LoginFrame.getContentPane());
        LoginFrame.getContentPane().setLayout(LoginFrameLayout);
        LoginFrameLayout.setHorizontalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFrameLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(usertf1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pf1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(179, 179, 179))
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton7)
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel16)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        LoginFrameLayout.setVerticalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usertf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(36, 36, 36))
        );

        Signup_Frame.setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14));
        jLabel4.setText("Enter Your Name");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14));
        jLabel5.setText("Enter Your username");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14));
        jLabel6.setText("Enter Your Password");

        nametf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametf1ActionPerformed(evt);
            }
        });

        jButton8.setText("Create Account");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Signup_FrameLayout = new javax.swing.GroupLayout(Signup_Frame.getContentPane());
        Signup_Frame.getContentPane().setLayout(Signup_FrameLayout);
        Signup_FrameLayout.setHorizontalGroup(
            Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Signup_FrameLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton8)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(Signup_FrameLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pwdf1, 0, 0, Short.MAX_VALUE)
                    .addComponent(usernametf1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(nametf1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        Signup_FrameLayout.setVerticalGroup(
            Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Signup_FrameLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nametf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernametf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Signup_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pwdf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton8)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        Issue_frame.setMinimumSize(new java.awt.Dimension(300, 400));
        Issue_frame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                Issue_frameWindowActivated(evt);
            }
        });

        jButton9.setText("ISSUE BOOK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "'0011','FAMOUS FIVE PART-1", "'0012','FAMOUS FIVE PART-1", "'0021','FAMOUS FIVE PART-1", "'0022','FAMOUS FIVE PART-1", "'0031','FAMOUS FIVE PART-1", "'0032','FAMOUS FIVE PART-1", "'0041','FAMOUS FIVE PART-1", "'0042','FAMOUS FIVE PART-1", "'0051','FAMOUS FIVE PART-1", "'0052','FAMOUS FIVE PART-1", "'0011','SECRET SEVEN-1", "'1012','SECRET SEVEN-1", "'1021','SECRET SEVEN-2", "'1022','SECRET SEVEN-2", "'1031','SECRET SEVEN-3", "'1032','SECRET SEVEN-3", "'0011','SECRET SEVEN-1'0011','SECRET SEVEN-1" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JK ROWLING", "ENID BLYTON" }));

        jLabel8.setText("BOOK NAME");

        jLabel9.setText("AUTHOR NAME");

        jLabel10.setText("ISSUE PORTAL");

        javax.swing.GroupLayout Issue_frameLayout = new javax.swing.GroupLayout(Issue_frame.getContentPane());
        Issue_frame.getContentPane().setLayout(Issue_frameLayout);
        Issue_frameLayout.setHorizontalGroup(
            Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Issue_frameLayout.createSequentialGroup()
                .addGroup(Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Issue_frameLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel10))
                    .addGroup(Issue_frameLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(149, 149, 149)
                        .addGroup(Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(Issue_frameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(87, 87, 87))
        );
        Issue_frameLayout.setVerticalGroup(
            Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Issue_frameLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addGap(125, 125, 125)
                .addGroup(Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144)
                .addGroup(Issue_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        return_frame.setMinimumSize(new java.awt.Dimension(300, 400));
        return_frame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                return_frameWindowActivated(evt);
            }
        });

        jButton11.setText("RETURN BOOK");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("BACK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel11.setText("RETURN BOOK PORTAL");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "'0011','FAMOUS FIVE PART-1", "'0012','FAMOUS FIVE PART-1", "'0021','FAMOUS FIVE PART-1", "'0022','FAMOUS FIVE PART-1", "'0031','FAMOUS FIVE PART-1", "'0032','FAMOUS FIVE PART-1", "'0041','FAMOUS FIVE PART-1", "'0042','FAMOUS FIVE PART-1", "'0051','FAMOUS FIVE PART-1", "'0052','FAMOUS FIVE PART-1", "'0011','SECRET SEVEN-1", "'1012','SECRET SEVEN-1", "'1021','SECRET SEVEN-2", "'1022','SECRET SEVEN-2", "'1031','SECRET SEVEN-3", "'1032','SECRET SEVEN-3", "'0011','SECRET SEVEN-1'0011','SECRET SEVEN-1" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JK ROWLING", "ENID BLYTON" }));

        javax.swing.GroupLayout return_frameLayout = new javax.swing.GroupLayout(return_frame.getContentPane());
        return_frame.getContentPane().setLayout(return_frameLayout);
        return_frameLayout.setHorizontalGroup(
            return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, return_frameLayout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(278, 278, 278))
            .addGroup(return_frameLayout.createSequentialGroup()
                .addGroup(return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, return_frameLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(126, 126, 126)
                        .addGroup(return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(return_frameLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        return_frameLayout.setVerticalGroup(
            return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(return_frameLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addGap(98, 98, 98)
                .addGroup(return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(return_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, return_frameLayout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, return_frameLayout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(132, 132, 132))))
        );

        jLabel7.setText("COMING SOON");

        javax.swing.GroupLayout pay_frameLayout = new javax.swing.GroupLayout(pay_frame.getContentPane());
        pay_frame.getContentPane().setLayout(pay_frameLayout);
        pay_frameLayout.setHorizontalGroup(
            pay_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_frameLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel7)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        pay_frameLayout.setVerticalGroup(
            pay_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_frameLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel7)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        dashboard.setMinimumSize(new java.awt.Dimension(300, 400));

        jButton13.setText("ISSUE BOOK");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("LOG OUT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("PAYMENT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("RETURN BOOK");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel14.setText("DASH BOARD");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard.getContentPane());
        dashboard.getContentPane().setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addGap(58, 58, 58))
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel14)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addGap(62, 62, 62)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        jLabel1.setText("Library Management System");

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 14));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 14));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
Signup_Frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        LoginFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Connection con = null;
Statement stmt = null;
ResultSet rs = null;

        String Name= nametf1.getText();
       String Username= usernametf1.getText();
       String Password = new String(pwdf1.getPassword());
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
   stmt = con.createStatement();
    String sql = "INSERT INTO User(Name, UserID, Pass)VALUES ('" + Name + "', '" + Username + "', '" + Password + "');";
    System.out.println(sql);
    stmt.executeUpdate(sql);
    JOptionPane.showMessageDialog(rootPane, "Congrats! Account created successfully!");
    Signup_Frame.dispose();
    this.setVisible(true);
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void nametf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametf1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

         Connection con = null;
Statement stmt = null;
ResultSet rs = null;

        
        String uid = usertf1.getText();
String pwd = new String(pf1.getPassword());
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
    stmt = con.createStatement();
    String sql = "SELECT Pass FROM User WHERE UserID = '" + uid + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
    String pass = rs.getString(1);
    if(pwd.equals(pass)){
        LoginFrame.dispose();
        currentUserID = uid;
        dashboard.setVisible(true);
    }
    else{
    JOptionPane.showMessageDialog(null, "See, your userID or password is wrong. Try again!");
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
String author = (String)jComboBox2.getSelectedItem();
String book = (String)jComboBox1.getSelectedItem();
Connection con = null;
Statement stmt = null;
ResultSet rs = null;
try
{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
stmt = con.createStatement();
String sql = "SELECT BOOKID FROM bookname WHERE AUTHOR = '"+author+"' AND NAME = '"+book+"' AND ISSUED = 0 ;";
    System.out.println(sql);
rs = stmt.executeQuery(sql);
if(rs.first())
{
	String bookid = rs.getString("BOOKID");
    String sql2 = "UPDATE bookname SET ISSUED = 1 WHERE BOOKID ='" + bookid+"';";
    stmt.executeUpdate(sql2);

String sql3 = "INSERT INTO transaction(BOOK_ID,USER_ID,EXPECTED_DATE)VALUES ('" + bookid + "', '" + currentUserID + " ', DATE(curdate()+7));";

stmt.executeUpdate(sql3);
 System.out.println(sql3);JOptionPane.showMessageDialog(rootPane, "Book Issued");

}

else
{
	JOptionPane.showMessageDialog(rootPane, "Incorrect  Book or Author");
}
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
String author = (String)jComboBox3.getSelectedItem();
String book = (String)jComboBox4.getSelectedItem();
Connection con = null;
Statement stmt = null;
ResultSet rs = null;
try
{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
stmt = con.createStatement();
String sql = "SELECT BOOKID FROM bookname WHERE AUTHOR = '"+author+"' AND NAME = '"+book+"' AND ISSUED = 1 ;";
    System.out.println(sql);
rs = stmt.executeQuery(sql);
if(rs.first())
{
	String bookid = rs.getString("BOOKID");
    String sql2 = "UPDATE bookname SET ISSUED = 0 WHERE BOOKID ='" + bookid+"';";
    stmt.executeUpdate(sql2);
	JOptionPane.showMessageDialog(rootPane, "Book Returned Successfully");
}

else
{
	JOptionPane.showMessageDialog(rootPane, "Incorrect  Book or Author");
}
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
this.dispose();
Issue_frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
this.dispose();
return_frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
this.dispose();
LoginFrame.setVisible(true);
usertf1.setText("");
pf1.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
this.dispose();
pay_frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void Issue_frameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Issue_frameWindowActivated


jComboBox2.removeAllItems();
jComboBox1.removeAllItems();
jComboBox2.addItem("--Select Author--");
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
    stmt = con.createStatement();
    String sql = "SELECT DISTINCT AUTHOR FROM bookname ORDER BY AUTHOR ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
        jComboBox2.addItem(rs.getString("AUTHOR"));
    }
    jComboBox2.setSelectedItem("--Select Author--");
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
    stmt = con.createStatement();
    jComboBox1.addItem("--Select Book--");
    String sql = "SELECT DISTINCT NAME FROM bookname ORDER BY NAME ASC;";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
        jComboBox1.addItem(rs.getString("NAME"));
    }
    jComboBox1.setSelectedItem("--Select Book--");
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_Issue_frameWindowActivated

    private void return_frameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_return_frameWindowActivated
        jComboBox3.removeAllItems();
        jComboBox4.removeAllItems();
        jComboBox3.addItem("--Select Author--");
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
    stmt = con.createStatement();
    String sql = "SELECT AUTHOR FROM bookname WHERE BOOKID =(SELECT BOOK_ID FROM transaction WHERE USER_ID = '"+ currentUserID +"') AND ISSUED=1";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
        jComboBox3.addItem(rs.getString("AUTHOR"));
    }
    jComboBox3.setSelectedItem("--Select Author--");
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
        try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/LBMS", "root", "123456");
    stmt = con.createStatement();
    String sql = "SELECT NAME FROM bookname WHERE BOOKID =(SELECT BOOK_ID FROM transaction WHERE USER_ID = '"+ currentUserID +"') AND ISSUED=1";
    rs = stmt.executeQuery(sql);
    while(rs.next()){
        jComboBox4.addItem(rs.getString("NAME"));
    }
    jComboBox4.setSelectedItem("--Select BOOK--");
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}

    }//GEN-LAST:event_return_frameWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Issue_frame;
    private javax.swing.JFrame LoginFrame;
    private javax.swing.JFrame Signup_Frame;
    private javax.swing.JFrame dashboard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nametf1;
    private javax.swing.JFrame pay_frame;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pwdf1;
    private javax.swing.JFrame return_frame;
    private javax.swing.JTextField usernametf1;
    private javax.swing.JTextField usertf1;
    // End of variables declaration//GEN-END:variables

}
