import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on 12 May, 2020, 9:13:38 PM
 */

/**
 *
 * @author Saish Mendke
 */

public class login extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs = null;
DefaultTableModel tm = null;
String currentName = null;
String nameToView = null;
String dish = null;
String price = null;
String hotel = null;
String city = null;
int balance = 0;
String t= null;
String d=null;

    /** Creates new form login */
    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerDashboard = new javax.swing.JFrame();
        yourProfileButton = new javax.swing.JButton();
        searchUsersButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        searchFrame = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        profileFrame = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        collegeLabel = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        customerFrame = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        customerLogin = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NC2 = new javax.swing.JTextField();
        PC2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        hotelFrame = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        customerSignUp = new javax.swing.JFrame();
        jLabel24 = new javax.swing.JLabel();
        NC1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        AC1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        CC1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        PC1 = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        hotelSignUp = new javax.swing.JFrame();
        HN2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        HC2 = new javax.swing.JTextField();
        HP2 = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        hotelLogin = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        HN1 = new javax.swing.JTextField();
        HP1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        hotelDashboard = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        orderFrame = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dishLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        customerOrders = new javax.swing.JFrame();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        hotelOrders = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton25 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cancelOrderFrame = new javax.swing.JFrame();
        jLabel30 = new javax.swing.JLabel();
        dishLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        addMenuFrame = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        addDish = new javax.swing.JTextField();
        addPrice = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        walletFrame = new javax.swing.JFrame();
        jLabel55 = new javax.swing.JLabel();
        balance1 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        addMoneyFrame = new javax.swing.JFrame();
        jLabel56 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        hotelMenuFrame = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel60 = new javax.swing.JLabel();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();

        customerDashboard.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        customerDashboard.setMinimumSize(new java.awt.Dimension(520, 690));
        customerDashboard.getContentPane().setLayout(null);

        yourProfileButton.setFont(new java.awt.Font("Arial", 1, 18));
        yourProfileButton.setText("Your Profile");
        yourProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourProfileButtonActionPerformed(evt);
            }
        });
        customerDashboard.getContentPane().add(yourProfileButton);
        yourProfileButton.setBounds(70, 190, 150, 50);

        searchUsersButton.setFont(new java.awt.Font("Arial", 1, 18));
        searchUsersButton.setText("Check Menu");
        searchUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUsersButtonActionPerformed(evt);
            }
        });
        customerDashboard.getContentPane().add(searchUsersButton);
        searchUsersButton.setBounds(70, 310, 150, 50);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel9.setText("DASHBOARD");
        customerDashboard.getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 90, 160, 40);

        jButton11.setFont(new java.awt.Font("Arial", 1, 18));
        jButton11.setText("See your Orders");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        customerDashboard.getContentPane().add(jButton11);
        jButton11.setBounds(280, 310, 180, 50);

        jButton18.setFont(new java.awt.Font("Arial", 1, 18));
        jButton18.setText("Sign Out");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        customerDashboard.getContentPane().add(jButton18);
        jButton18.setBounds(300, 190, 120, 50);

        jButton23.setFont(new java.awt.Font("Arial", 1, 18));
        jButton23.setText("Cancel Order");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        customerDashboard.getContentPane().add(jButton23);
        jButton23.setBounds(290, 430, 160, 50);

        jButton31.setFont(new java.awt.Font("Arial", 1, 18));
        jButton31.setText("Wallet");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        customerDashboard.getContentPane().add(jButton31);
        jButton31.setBounds(100, 430, 100, 50);

        jLabel43.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel43.setText("jLabel43");
        customerDashboard.getContentPane().add(jLabel43);
        jLabel43.setBounds(0, -160, 550, 820);

        searchFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        searchFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                searchFrameWindowActivated(evt);
            }
        });
        searchFrame.getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel16.setText("Hotel ");
        searchFrame.getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 100, 60, 30);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 18));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select hotel--", "" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        searchFrame.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(90, 100, 160, 30);

        searchButton.setFont(new java.awt.Font("Arial", 1, 18));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchFrame.getContentPane().add(searchButton);
        searchButton.setBounds(333, 95, 110, 40);

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Arial", 1, 18));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dish", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchFrame.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 452, 402);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel12.setText("MENU");
        searchFrame.getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 30, 110, 40);

        jButton21.setFont(new java.awt.Font("Arial", 1, 18));
        jButton21.setText("Back to Dashboard");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        searchFrame.getContentPane().add(jButton21);
        jButton21.setBounds(170, 580, 200, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel45.setText("jLabel45");
        searchFrame.getContentPane().add(jLabel45);
        jLabel45.setBounds(0, 0, 570, 680);

        profileFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        profileFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                profileFrameWindowActivated(evt);
            }
        });
        profileFrame.getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel11.setText("Here is your profile!");
        profileFrame.getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 60, 360, 70);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel13.setText("Name:");
        profileFrame.getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 159, 80, 40);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel14.setText("City :");
        profileFrame.getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 240, 60, 29);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 24));
        nameLabel.setText("< User name goes here >");
        profileFrame.getContentPane().add(nameLabel);
        nameLabel.setBounds(170, 159, 310, 40);

        collegeLabel.setFont(new java.awt.Font("Arial", 1, 24));
        collegeLabel.setText("< City goes here >");
        profileFrame.getContentPane().add(collegeLabel);
        collegeLabel.setBounds(170, 229, 230, 50);

        jButton20.setFont(new java.awt.Font("Arial", 1, 18));
        jButton20.setText("Back to Dashboard");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        profileFrame.getContentPane().add(jButton20);
        jButton20.setBounds(140, 360, 210, 60);

        jLabel44.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel44.setText("jLabel44");
        profileFrame.getContentPane().add(jLabel44);
        jLabel44.setBounds(0, -160, 560, 830);

        customerFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        customerFrame.setMinimumSize(new java.awt.Dimension(500, 350));
        customerFrame.getContentPane().setLayout(null);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        customerFrame.getContentPane().add(jButton1);
        jButton1.setBounds(270, 180, 80, 25);

        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        customerFrame.getContentPane().add(jButton2);
        jButton2.setBounds(370, 180, 90, 25);

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        customerFrame.getContentPane().add(jButton12);
        jButton12.setBounds(320, 230, 80, 25);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel38.setText("Welcome Customer!");
        customerFrame.getContentPane().add(jLabel38);
        jLabel38.setBounds(30, 100, 250, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\Webp.net-resizeimage (1).jpg")); // NOI18N
        jLabel35.setText("jLabel35");
        customerFrame.getContentPane().add(jLabel35);
        jLabel35.setBounds(0, -70, 580, 440);

        customerLogin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        customerLogin.setMinimumSize(new java.awt.Dimension(500, 690));
        customerLogin.getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Name :");
        customerLogin.getContentPane().add(jLabel17);
        jLabel17.setBounds(100, 170, 70, 22);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Password :");
        customerLogin.getContentPane().add(jLabel18);
        jLabel18.setBounds(70, 220, 110, 22);
        customerLogin.getContentPane().add(NC2);
        NC2.setBounds(180, 170, 170, 20);
        customerLogin.getContentPane().add(PC2);
        PC2.setBounds(180, 220, 170, 22);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        customerLogin.getContentPane().add(jButton3);
        jButton3.setBounds(110, 355, 100, 40);

        jButton14.setFont(new java.awt.Font("Arial", 1, 18));
        jButton14.setText("Back");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        customerLogin.getContentPane().add(jButton14);
        jButton14.setBounds(270, 355, 100, 40);

        jLabel64.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("CUSTOMER LOGIN");
        customerLogin.getContentPane().add(jLabel64);
        jLabel64.setBounds(140, 70, 240, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\Webp.net-resizeimage (2).jpg")); // NOI18N
        jLabel36.setText("jLabel36");
        customerLogin.getContentPane().add(jLabel36);
        jLabel36.setBounds(0, -160, 480, 800);

        hotelFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        hotelFrame.setMinimumSize(new java.awt.Dimension(550, 350));
        hotelFrame.getContentPane().setLayout(null);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14));
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        hotelFrame.getContentPane().add(jButton4);
        jButton4.setBounds(280, 165, 80, 30);

        jButton5.setFont(new java.awt.Font("Arial", 1, 14));
        jButton5.setText("Sign Up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        hotelFrame.getContentPane().add(jButton5);
        jButton5.setBounds(380, 165, 90, 30);

        jButton13.setFont(new java.awt.Font("Arial", 1, 14));
        jButton13.setText("Back");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        hotelFrame.getContentPane().add(jButton13);
        jButton13.setBounds(330, 220, 70, 25);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel39.setText("WELCOME HOTEL!");
        hotelFrame.getContentPane().add(jLabel39);
        jLabel39.setBounds(30, 110, 240, 30);

        jLabel42.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\Webp.net-resizeimage (1).jpg")); // NOI18N
        jLabel42.setText("jLabel42");
        hotelFrame.getContentPane().add(jLabel42);
        jLabel42.setBounds(0, 0, 550, 300);

        customerSignUp.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        customerSignUp.setMinimumSize(new java.awt.Dimension(500, 690));
        customerSignUp.getContentPane().setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Name :");
        customerSignUp.getContentPane().add(jLabel24);
        jLabel24.setBounds(102, 210, 70, 22);
        customerSignUp.getContentPane().add(NC1);
        NC1.setBounds(190, 210, 150, 22);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Age :");
        customerSignUp.getContentPane().add(jLabel25);
        jLabel25.setBounds(121, 260, 50, 22);
        customerSignUp.getContentPane().add(AC1);
        AC1.setBounds(190, 260, 150, 22);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("City :");
        customerSignUp.getContentPane().add(jLabel26);
        jLabel26.setBounds(120, 310, 50, 22);
        customerSignUp.getContentPane().add(CC1);
        CC1.setBounds(190, 310, 150, 22);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Password :");
        customerSignUp.getContentPane().add(jLabel27);
        jLabel27.setBounds(70, 350, 100, 22);
        customerSignUp.getContentPane().add(PC1);
        PC1.setBounds(190, 350, 150, 22);

        jButton8.setFont(new java.awt.Font("Arial", 1, 18));
        jButton8.setText("Create Account!");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        customerSignUp.getContentPane().add(jButton8);
        jButton8.setBounds(60, 420, 190, 50);

        jButton16.setFont(new java.awt.Font("Arial", 1, 18));
        jButton16.setText("Back");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        customerSignUp.getContentPane().add(jButton16);
        jButton16.setBounds(280, 415, 160, 50);

        jLabel63.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("CUSTOMER SIGN-UP");
        customerSignUp.getContentPane().add(jLabel63);
        jLabel63.setBounds(130, 100, 250, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\Webp.net-resizeimage (2).jpg")); // NOI18N
        jLabel40.setText("jLabel40");
        customerSignUp.getContentPane().add(jLabel40);
        jLabel40.setBounds(0, -230, 600, 910);

        hotelSignUp.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        hotelSignUp.setMinimumSize(new java.awt.Dimension(500, 690));
        hotelSignUp.getContentPane().setLayout(null);
        hotelSignUp.getContentPane().add(HN2);
        HN2.setBounds(180, 210, 140, 22);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Name :");
        hotelSignUp.getContentPane().add(jLabel21);
        jLabel21.setBounds(110, 210, 63, 22);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("City :");
        hotelSignUp.getContentPane().add(jLabel22);
        jLabel22.setBounds(120, 260, 50, 22);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Password :");
        hotelSignUp.getContentPane().add(jLabel23);
        jLabel23.setBounds(74, 310, 100, 22);
        hotelSignUp.getContentPane().add(HC2);
        HC2.setBounds(180, 260, 140, 22);
        hotelSignUp.getContentPane().add(HP2);
        HP2.setBounds(180, 310, 140, 22);

        jButton7.setFont(new java.awt.Font("Arial", 1, 18));
        jButton7.setText("Register");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        hotelSignUp.getContentPane().add(jButton7);
        jButton7.setBounds(100, 385, 110, 40);

        jButton17.setFont(new java.awt.Font("Arial", 1, 18));
        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        hotelSignUp.getContentPane().add(jButton17);
        jButton17.setBounds(290, 385, 90, 40);

        jLabel62.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("HOTEL SIGN-UP");
        hotelSignUp.getContentPane().add(jLabel62);
        jLabel62.setBounds(150, 80, 200, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\Webp.net-resizeimage (2).jpg")); // NOI18N
        jLabel41.setText("jLabel41");
        hotelSignUp.getContentPane().add(jLabel41);
        jLabel41.setBounds(0, -220, 550, 880);

        hotelLogin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        hotelLogin.setMinimumSize(new java.awt.Dimension(500, 690));
        hotelLogin.getContentPane().setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Name :");
        hotelLogin.getContentPane().add(jLabel19);
        jLabel19.setBounds(120, 190, 70, 16);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Password :");
        hotelLogin.getContentPane().add(jLabel20);
        jLabel20.setBounds(89, 240, 100, 22);
        hotelLogin.getContentPane().add(HN1);
        HN1.setBounds(190, 190, 130, 22);
        hotelLogin.getContentPane().add(HP1);
        HP1.setBounds(190, 240, 130, 22);

        jButton6.setFont(new java.awt.Font("Arial", 1, 18));
        jButton6.setText("Login");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        hotelLogin.getContentPane().add(jButton6);
        jButton6.setBounds(120, 350, 100, 50);

        jButton15.setFont(new java.awt.Font("Arial", 1, 18));
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        hotelLogin.getContentPane().add(jButton15);
        jButton15.setBounds(280, 355, 90, 40);

        jLabel65.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("HOTEL LOGIN");
        hotelLogin.getContentPane().add(jLabel65);
        jLabel65.setBounds(160, 80, 180, 40);

        jLabel37.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\Webp.net-resizeimage (2).jpg")); // NOI18N
        jLabel37.setText("jLabel37");
        hotelLogin.getContentPane().add(jLabel37);
        jLabel37.setBounds(0, -260, 500, 960);

        hotelDashboard.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        hotelDashboard.setMinimumSize(new java.awt.Dimension(520, 690));
        hotelDashboard.getContentPane().setLayout(null);

        jButton9.setFont(new java.awt.Font("Arial", 1, 18));
        jButton9.setText(" Check Orders");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        hotelDashboard.getContentPane().add(jButton9);
        jButton9.setBounds(60, 280, 170, 40);

        jButton19.setFont(new java.awt.Font("Arial", 1, 18));
        jButton19.setText("Sign Out");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        hotelDashboard.getContentPane().add(jButton19);
        jButton19.setBounds(80, 380, 130, 50);

        jButton26.setFont(new java.awt.Font("Arial", 1, 18));
        jButton26.setText("Add Menu");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        hotelDashboard.getContentPane().add(jButton26);
        jButton26.setBounds(290, 280, 140, 40);

        jButton36.setFont(new java.awt.Font("Arial", 1, 18));
        jButton36.setText("See Menu");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        hotelDashboard.getContentPane().add(jButton36);
        jButton36.setBounds(290, 380, 130, 50);

        jLabel48.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel48.setText("jLabel48");
        hotelDashboard.getContentPane().add(jLabel48);
        jLabel48.setBounds(0, -170, 580, 840);

        orderFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        orderFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        orderFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                orderFrameWindowActivated(evt);
            }
        });
        orderFrame.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel15.setText("Dish :");
        orderFrame.getContentPane().add(jLabel15);
        jLabel15.setBounds(100, 160, 51, 22);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel28.setText("Price :");
        orderFrame.getContentPane().add(jLabel28);
        jLabel28.setBounds(90, 230, 57, 22);

        dishLabel.setFont(new java.awt.Font("Arial", 1, 18));
        dishLabel.setText("<Dish gets displayed here >");
        orderFrame.getContentPane().add(dishLabel);
        dishLabel.setBounds(170, 160, 270, 30);

        priceLabel.setFont(new java.awt.Font("Arial", 1, 18));
        priceLabel.setText("< Price >");
        orderFrame.getContentPane().add(priceLabel);
        priceLabel.setBounds(170, 230, 90, 20);

        jButton10.setFont(new java.awt.Font("Arial", 1, 18));
        jButton10.setText("Order");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        orderFrame.getContentPane().add(jButton10);
        jButton10.setBounds(80, 320, 140, 40);

        jButton29.setFont(new java.awt.Font("Arial", 1, 18));
        jButton29.setText("Cancel");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        orderFrame.getContentPane().add(jButton29);
        jButton29.setBounds(290, 320, 110, 40);

        jLabel46.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel46.setText("jLabel46");
        orderFrame.getContentPane().add(jLabel46);
        jLabel46.setBounds(0, -120, 540, 790);

        customerOrders.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        customerOrders.setBounds(new java.awt.Rectangle(0, 0, 520, 690));
        customerOrders.setMinimumSize(new java.awt.Dimension(520, 690));
        customerOrders.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                customerOrdersWindowActivated(evt);
            }
        });
        customerOrders.getContentPane().setLayout(null);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel29.setText("Here are your Orders!");
        customerOrders.getContentPane().add(jLabel29);
        jLabel29.setBounds(60, 40, 390, 40);

        jTable2.setFont(new java.awt.Font("Arial", 1, 14));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hotel Name", "Dish", "Price", "Time", "Date"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        customerOrders.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 100, 452, 402);

        jButton22.setFont(new java.awt.Font("Arial", 1, 18));
        jButton22.setText("Back to Dashboard");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        customerOrders.getContentPane().add(jButton22);
        jButton22.setBounds(130, 580, 210, 40);

        jLabel54.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel54.setText("Total Price:");
        customerOrders.getContentPane().add(jLabel54);
        jLabel54.setBounds(250, 520, 100, 20);

        totalLabel.setFont(new java.awt.Font("Arial", 1, 18));
        totalLabel.setText("<Total price>");
        customerOrders.getContentPane().add(totalLabel);
        totalLabel.setBounds(350, 520, 120, 22);

        jLabel47.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel47.setText("jLabel47");
        customerOrders.getContentPane().add(jLabel47);
        jLabel47.setBounds(0, -100, 570, 760);

        hotelOrders.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        hotelOrders.setMinimumSize(new java.awt.Dimension(520, 690));
        hotelOrders.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                hotelOrdersWindowActivated(evt);
            }
        });
        hotelOrders.getContentPane().setLayout(null);

        jTable3.setFont(new java.awt.Font("Arial", 1, 14));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dish", "Price", "Time", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        hotelOrders.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 110, 452, 402);

        jButton25.setFont(new java.awt.Font("Arial", 1, 18));
        jButton25.setText("Back to Dashboard");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        hotelOrders.getContentPane().add(jButton25);
        jButton25.setBounds(129, 540, 210, 50);

        jLabel50.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel50.setText("Here are your Orders");
        hotelOrders.getContentPane().add(jLabel50);
        jLabel50.setBounds(130, 60, 240, 30);

        jLabel49.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel49.setText("jLabel49");
        hotelOrders.getContentPane().add(jLabel49);
        jLabel49.setBounds(0, -90, 500, 760);

        cancelOrderFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        cancelOrderFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        cancelOrderFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                cancelOrderFrameWindowActivated(evt);
            }
        });
        cancelOrderFrame.getContentPane().setLayout(null);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel30.setText("Dish :");
        cancelOrderFrame.getContentPane().add(jLabel30);
        jLabel30.setBounds(123, 226, 60, 20);

        dishLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        dishLabel1.setText("<Dish name>");
        cancelOrderFrame.getContentPane().add(dishLabel1);
        dishLabel1.setBounds(190, 220, 120, 30);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel32.setText("Price :");
        cancelOrderFrame.getContentPane().add(jLabel32);
        jLabel32.setBounds(120, 300, 57, 22);

        priceLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        priceLabel1.setText("<price of dish>");
        cancelOrderFrame.getContentPane().add(priceLabel1);
        priceLabel1.setBounds(190, 300, 130, 22);

        jButton24.setFont(new java.awt.Font("Arial", 1, 18));
        jButton24.setText("Cancel Order");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        cancelOrderFrame.getContentPane().add(jButton24);
        jButton24.setBounds(70, 420, 160, 50);

        jButton30.setFont(new java.awt.Font("Arial", 1, 18));
        jButton30.setText("Back");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        cancelOrderFrame.getContentPane().add(jButton30);
        jButton30.setBounds(290, 420, 140, 50);

        jLabel51.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel51.setText("jLabel51");
        cancelOrderFrame.getContentPane().add(jLabel51);
        jLabel51.setBounds(0, -130, 500, 790);

        addMenuFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMenuFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        addMenuFrame.getContentPane().setLayout(null);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel31.setText("Dish :");
        addMenuFrame.getContentPane().add(jLabel31);
        jLabel31.setBounds(130, 230, 51, 22);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel33.setText("Price :");
        addMenuFrame.getContentPane().add(jLabel33);
        jLabel33.setBounds(120, 290, 60, 20);
        addMenuFrame.getContentPane().add(addDish);
        addDish.setBounds(190, 228, 150, 22);
        addMenuFrame.getContentPane().add(addPrice);
        addPrice.setBounds(190, 290, 150, 22);

        jButton27.setFont(new java.awt.Font("Arial", 1, 18));
        jButton27.setText("Add Menu");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        addMenuFrame.getContentPane().add(jButton27);
        jButton27.setBounds(80, 430, 140, 50);

        jButton28.setFont(new java.awt.Font("Arial", 1, 18));
        jButton28.setText("Back to Dashboard");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        addMenuFrame.getContentPane().add(jButton28);
        jButton28.setBounds(250, 430, 220, 50);

        jLabel53.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel53.setText("Update Menu");
        addMenuFrame.getContentPane().add(jLabel53);
        jLabel53.setBounds(170, 90, 160, 50);

        jLabel52.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel52.setText("jLabel52");
        addMenuFrame.getContentPane().add(jLabel52);
        jLabel52.setBounds(0, -90, 550, 760);

        walletFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        walletFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        walletFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                walletFrameWindowActivated(evt);
            }
        });
        walletFrame.getContentPane().setLayout(null);

        jLabel55.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel55.setText("Balance :");
        walletFrame.getContentPane().add(jLabel55);
        jLabel55.setBounds(120, 220, 120, 40);

        balance1.setFont(new java.awt.Font("Arial", 1, 24));
        balance1.setText("< Balance >");
        walletFrame.getContentPane().add(balance1);
        balance1.setBounds(240, 230, 140, 29);

        jButton32.setFont(new java.awt.Font("Arial", 1, 18));
        jButton32.setText("Add Money");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        walletFrame.getContentPane().add(jButton32);
        jButton32.setBounds(70, 340, 150, 60);

        jButton33.setFont(new java.awt.Font("Arial", 1, 18));
        jButton33.setText("Back to Dashboard");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        walletFrame.getContentPane().add(jButton33);
        jButton33.setBounds(260, 340, 200, 60);

        jLabel59.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel59.setText("Here is your wallet!");
        walletFrame.getContentPane().add(jLabel59);
        jLabel59.setBounds(100, 60, 330, 50);

        jLabel57.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel57.setText("jLabel57");
        walletFrame.getContentPane().add(jLabel57);
        jLabel57.setBounds(0, -140, 550, 800);

        addMoneyFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMoneyFrame.setMinimumSize(new java.awt.Dimension(520, 690));
        addMoneyFrame.getContentPane().setLayout(null);

        jLabel56.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel56.setText("Enter Amount :");
        addMoneyFrame.getContentPane().add(jLabel56);
        jLabel56.setBounds(80, 230, 180, 29);
        addMoneyFrame.getContentPane().add(amount);
        amount.setBounds(270, 232, 140, 30);

        jButton34.setFont(new java.awt.Font("Arial", 1, 18));
        jButton34.setText("Add money");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        addMoneyFrame.getContentPane().add(jButton34);
        jButton34.setBounds(90, 360, 150, 50);

        jButton35.setFont(new java.awt.Font("Arial", 1, 18));
        jButton35.setText("Back");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        addMoneyFrame.getContentPane().add(jButton35);
        jButton35.setBounds(310, 360, 100, 50);

        jLabel58.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel58.setText("jLabel58");
        addMoneyFrame.getContentPane().add(jLabel58);
        jLabel58.setBounds(0, -90, 540, 760);

        hotelMenuFrame.setMinimumSize(new java.awt.Dimension(520, 700));
        hotelMenuFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                hotelMenuFrameWindowActivated(evt);
            }
        });
        hotelMenuFrame.getContentPane().setLayout(null);

        jTable4.setFont(new java.awt.Font("Arial", 1, 14));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish", "Price"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        hotelMenuFrame.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(20, 110, 452, 402);

        jLabel60.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel60.setText("Here is your Menu");
        hotelMenuFrame.getContentPane().add(jLabel60);
        jLabel60.setBounds(90, 30, 320, 50);

        jButton37.setFont(new java.awt.Font("Arial", 1, 18));
        jButton37.setText("Add a Dish");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        hotelMenuFrame.getContentPane().add(jButton37);
        jButton37.setBounds(60, 550, 140, 40);

        jButton38.setFont(new java.awt.Font("Arial", 1, 18));
        jButton38.setText("Back to Dashboard");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        hotelMenuFrame.getContentPane().add(jButton38);
        jButton38.setBounds(240, 550, 210, 40);

        jLabel61.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\back_dash1.jpg")); // NOI18N
        jLabel61.setText("jLabel61");
        hotelMenuFrame.getContentPane().add(jLabel61);
        jLabel61.setBounds(0, -100, 590, 790);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 40, 90, 16);

        signUpButton.setText("Customer");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(250, 100, 120, 25);

        loginButton.setText("Hotel");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(250, 160, 120, 25);

        jLabel34.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images\\background_food_app.jpg")); // NOI18N
        jLabel34.setText("jLabel34");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(0, -20, 460, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        customerFrame.setVisible(true);
        
}//GEN-LAST:event_signUpButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        hotelFrame.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void yourProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourProfileButtonActionPerformed
        // TODO add your handling code here:
        //userToView = currentUserID;
        customerDashboard.dispose();
        profileFrame.setVisible(true);
}//GEN-LAST:event_yourProfileButtonActionPerformed

    private void searchUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUsersButtonActionPerformed
        // TODO add your handling code here:
        customerDashboard.dispose();
        searchFrame.setVisible(true);
    }//GEN-LAST:event_searchUsersButtonActionPerformed

    private void profileFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_profileFrameWindowActivated
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT * FROM USER WHERE Name = '" + currentName + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            //userIDLabel.setText(rs.getString("UserID"));
            nameLabel.setText(rs.getString("Name"));
            collegeLabel.setText(rs.getString("City"));
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_profileFrameWindowActivated

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        tm.setRowCount(0);
        String hotel = (String)jComboBox2.getSelectedItem();
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
           String sql = "SELECT Hotel,Dish,Price FROM menu WHERE Hotel IN (select Name from hotel where City = '" + city + "');";
           if(hotel.equals("--Select hotel--")){
                sql = "SELECT Hotel,Dish,Price FROM menu WHERE Hotel IN (select Name from hotel where City = '" + city + "');";
            }
           else{
               sql = "SELECT Hotel,Dish,Price FROM menu WHERE Hotel = '" + hotel + "';";
           }
           rs = stmt.executeQuery(sql);
           System.out.println(sql);
           String[] rowdata=new String[3];
           while(rs.next()){
               System.out.println(rs.getString("Hotel")+ rs.getString("Dish")+ rs.getString("Price"));
               tm.addRow(new Object[]{rs.getString("Hotel"), rs.getString("Dish"), rs.getString("Price")});
           }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
}//GEN-LAST:event_searchButtonActionPerformed

    private void searchFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_searchFrameWindowActivated
        // TODO add your handling code here:
        tm = (DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        jComboBox2.removeAllItems();
        jComboBox2.addItem("--Select hotel--");
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
           //String sql1 = "Select City from user where Name = '" + currentName + "';";
           //rs = stmt.executeQuery(sql1);
           //city = rs.getString("City");
           //rs = null;
           String sql = "SELECT DISTINCT Name FROM hotel WHERE City = '" + city + "' ORDER BY Name ASC;";
           rs = stmt.executeQuery(sql);
            while(rs.next()){
               jComboBox2.addItem(rs.getString("Name"));
            }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_searchFrameWindowActivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        nameToView = (String)jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        hotel = (String)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        searchFrame.dispose();
        orderFrame.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        customerFrame.dispose();
        customerLogin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = NC2.getText();
        String pwd = new String(PC2.getPassword());
        currentName = name;
        try{
            System.out.println("hi");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            System.out.println("hi");
            stmt = con.createStatement();
            String sql = "SELECT Pass,City FROM user WHERE Name = '" + name + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            String pass = rs.getString(1);
            city = rs.getString(2);
            if(pwd.equals(pass)){
                NC2.setText("");
                PC2.setText("");
                customerLogin.dispose();
                customerDashboard.setVisible(true);
            }
            else{
                NC2.setText("");
                PC2.setText("");
                JOptionPane.showMessageDialog(null, "See, your Name or password is wrong. Try again!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String name = NC1.getText();
        String age = AC1.getText();
        String city = CC1.getText();
        String pwd = new String(PC1.getPassword());
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
        stmt = con.createStatement();
        String sql = "INSERT INTO user(Name, Age, City, Pass) VALUES('" + name + "', '" + age + "', '" + city + "', '" + pwd + "');";
        System.out.println(sql);
        stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Congrats! Account created successfully!");
        NC1.setText("");
        AC1.setText("");
        PC1.setText("");
        CC1.setText("");
        customerSignUp.dispose();
        customerFrame.setVisible(true);
        stmt.close();
        con.close();
        }
    catch(Exception e){
        NC1.setText("");
        AC1.setText("");
        PC1.setText("");
        CC1.setText("");
         JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        customerFrame.dispose();
        customerSignUp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hotelFrame.dispose();
        hotelLogin.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        hotelFrame.dispose();
        hotelSignUp.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String name = HN1.getText();
        String pwd = new String(HP1.getPassword());
        try{
            System.out.println("hi");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            System.out.println("hi");
            stmt = con.createStatement();
            String sql = "SELECT Pass FROM hotel WHERE Name = '" + name + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            String pass = rs.getString(1);
            if(pwd.equals(pass)){
                hotel = name;
                HN1.setText("");
                HP1.setText("");
                hotelLogin.dispose();
                hotelDashboard.setVisible(true);
            }
            else{
                HN1.setText("");
                HP1.setText("");
                JOptionPane.showMessageDialog(null, "See, your Name or password is wrong. Try again!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String name = HN2.getText();
        String city = HC2.getText();
        String pwd = new String(HP2.getPassword());
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
        stmt = con.createStatement();
        String sql = "INSERT INTO hotel(Name, City, Pass) VALUES('" + name + "', '" + city + "', '" + pwd + "');";
        System.out.println(sql);
        stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Congrats! Account created successfully!");
        HN2.setText("");
        HC2.setText("");
        HP2.setText("");
        stmt.close();
        con.close();
        hotelSignUp.dispose();
        hotelFrame.setVisible(true);
        }
    catch(Exception e){
        HN2.setText("");
        HC2.setText("");
        HP2.setText("");
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            if(balance >= Integer.parseInt(price)){
                String sql = "Insert into orders values('"+hotel+"','"+currentName+"','"+dish+"','"+price+"',curtime(),curdate());";
                System.out.println(sql);
                stmt.executeUpdate(sql);
                //rs.first();
                //rs.close();
                balance -= Integer.parseInt(price);
                sql = "update user set Balance ='" +balance+ "' where Name='"+currentName+"';";
                System.out.println(sql);
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Order Placed\ndish: "+dish+"\nprice: "+price);
                stmt.close();
                con.close();
                orderFrame.dispose();
                searchFrame.setVisible(true);}
            else{
                JOptionPane.showMessageDialog(null, "Insufficient Account Balance");
                orderFrame.dispose();
                searchFrame.setVisible(true);}
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void orderFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_orderFrameWindowActivated
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT * FROM menu WHERE (Dish = '" + nameToView + "' and Hotel = '" + hotel + "');";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            //userIDLabel.setText(rs.getString("UserID"));
            dishLabel.setText(rs.getString("Dish"));
            priceLabel.setText(rs.getString("Price"));
            dish = rs.getString("Dish");
            price = rs.getString("Price");
            hotel = rs.getString("Hotel");
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_orderFrameWindowActivated

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        customerDashboard.dispose();
        customerOrders.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void customerOrdersWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_customerOrdersWindowActivated
        // TODO add your handling code here:
        tm = (DefaultTableModel)jTable2.getModel();
        tm.setRowCount(0);
        int total= 0;
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
           String sql = "SELECT * FROM orders WHERE Name = '" + currentName + "';";
           rs = stmt.executeQuery(sql);
           System.out.println(sql);
           String[] rowdata=new String[5];
           while(rs.next()){
               System.out.println(rs.getString("Hotel")+ rs.getString("Dish")+ rs.getString("Price")+rs.getString("Time")+rs.getString("Date"));
               tm.addRow(new Object[]{rs.getString("Hotel"), rs.getString("Dish"), rs.getString("Price"),rs.getString("Time"),rs.getString("Date")});
               total += rs.getInt("Price");
           }
        totalLabel.setText(""+total);
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_customerOrdersWindowActivated

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        customerFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        hotelFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        NC2.setText("");
        PC2.setText("");
        customerLogin.dispose();
        customerFrame.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        HN1.setText("");
        HP1.setText("");
        hotelLogin.dispose();
        hotelFrame.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        NC1.setText("");
        AC1.setText("");
        PC1.setText("");
        AC1.setText("");
        customerSignUp.dispose();
        customerFrame.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        HN2.setText("");
        HC2.setText("");
        HP2.setText("");
        hotelSignUp.dispose();
        hotelFrame.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        customerDashboard.dispose();
        customerLogin.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        hotelDashboard.dispose();
        hotelFrame.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        hotelDashboard.dispose();
        hotelOrders.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void hotelOrdersWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_hotelOrdersWindowActivated
        // TODO add your handling code here:
        tm = (DefaultTableModel)jTable3.getModel();
        tm.setRowCount(0);
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
           String sql = "SELECT * FROM orders WHERE Hotel = '" + hotel + "';";
           rs = stmt.executeQuery(sql);
           System.out.println(sql);
           String[] rowdata=new String[5];
           while(rs.next()){
               System.out.println(rs.getString("Name")+ rs.getString("Dish")+ rs.getString("Price")+rs.getString("Time")+rs.getString("Date"));
               tm.addRow(new Object[]{rs.getString("Name"), rs.getString("Dish"), rs.getString("Price"), rs.getString("Time"), rs.getString("Date")});
           }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_hotelOrdersWindowActivated

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        profileFrame.dispose();
        customerDashboard.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        searchFrame.dispose();
        customerDashboard.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        customerOrders.dispose();
        customerDashboard.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        customerDashboard.dispose();
        customerOrders.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        nameToView = (String)jTable2.getValueAt(jTable2.getSelectedRow(), 1);
        hotel = (String)jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        price = (String)jTable2.getValueAt(jTable2.getSelectedRow(), 2);
        t = (String)jTable2.getValueAt(jTable2.getSelectedRow(), 3);
        d = (String)jTable2.getValueAt(jTable2.getSelectedRow(), 4);
        customerOrders.dispose();
        cancelOrderFrame.setVisible(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "DELETE FROM orders WHERE (Dish = '" + nameToView + "' and Name = '"+ currentName +"' and Time='"+t+"' and Date='"+d+"');";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            //rs.first();
            balance += Integer.parseInt(price);
            sql = "update user set Balance ='"+balance+"' WHERE Name = '"+ currentName +"';";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            //dish = rs.getString("Dish");
            //price = rs.getString("Price");
            //hotel = rs.getString("Hotel");
            //rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Order Cancelled Successfully.\nRs:"+Integer.parseInt(price)+" has been credited to your account");
            cancelOrderFrame.dispose();
            customerOrders.setVisible(true);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void cancelOrderFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cancelOrderFrameWindowActivated
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT * FROM menu WHERE Dish = '" + nameToView + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            //userIDLabel.setText(rs.getString("UserID"));
            dishLabel1.setText(nameToView);
            priceLabel1.setText(price);
            //dish = rs.getString("Dish");
            //price = rs.getString("Price");
            //hotel = rs.getString("Hotel");
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cancelOrderFrameWindowActivated

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        hotelOrders.dispose();
        hotelDashboard.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        dish = addDish.getText();
        price = addPrice.getText();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "Insert into menu values('"+hotel+"','"+dish+"','"+price+"');";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            //rs.first();
            //rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
        addDish.setText("");
        addPrice.setText("");
        JOptionPane.showMessageDialog(null, "Dish added successfully\ndish: "+dish+"\nprice: "+price);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        hotelDashboard.dispose();
        addMenuFrame.setVisible(true);

    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        addMenuFrame.dispose();
        hotelDashboard.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        orderFrame.dispose();
        searchFrame.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        cancelOrderFrame.dispose();
        customerOrders.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        customerDashboard.dispose();
        walletFrame.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void walletFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_walletFrameWindowActivated
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT * FROM user WHERE Name = '" + currentName + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            //System.out.println(rs.getInt("Balance"));
            balance = Integer.parseInt(rs.getString("Balance"));
            System.out.println(balance);
            balance1.setText(rs.getString("Balance"));
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_walletFrameWindowActivated

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        walletFrame.dispose();
        customerDashboard.setVisible(true);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        walletFrame.dispose();
        addMoneyFrame.setVisible(true);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        int amount1 = Integer.parseInt(amount.getText());
        if(amount1<0){
            JOptionPane.showMessageDialog(rootPane, "Please enter a positive number!");
            amount1=0;
        }
        balance += amount1;
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
        stmt = con.createStatement();
        String sql = "UPDATE user set Balance = '" + balance + "'where Name = '" +currentName+ "';";
        System.out.println(sql);
        stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(rootPane, "Money added successfully.\nBalance ="+balance);
        amount.setText("");
        stmt.close();
        con.close();
        }
    catch(Exception e){
         JOptionPane.showMessageDialog(null, e.getMessage());
        }
        addMoneyFrame.dispose();
        walletFrame.setVisible(true);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        addMoneyFrame.dispose();
        walletFrame.setVisible(true);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void hotelMenuFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_hotelMenuFrameWindowActivated
        // TODO add your handling code here:
        tm = (DefaultTableModel)jTable4.getModel();
        tm.setRowCount(0);
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
           String sql = "SELECT * FROM menu WHERE Hotel = '" + hotel + "';";
           rs = stmt.executeQuery(sql);
           System.out.println(sql);
           String[] rowdata=new String[5];
           while(rs.next()){
               System.out.println(rs.getString("Dish")+ rs.getString("Price"));
               tm.addRow(new Object[]{rs.getString("Dish"), rs.getString("Price")});
           }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_hotelMenuFrameWindowActivated

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        hotelMenuFrame.dispose();
        hotelDashboard.setVisible(true);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        hotelMenuFrame.dispose();
        addMenuFrame.setVisible(true);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        hotelDashboard.dispose();
        hotelMenuFrame.setVisible(true);
    }//GEN-LAST:event_jButton36ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AC1;
    private javax.swing.JTextField CC1;
    private javax.swing.JTextField HC2;
    private javax.swing.JTextField HN1;
    private javax.swing.JTextField HN2;
    private javax.swing.JPasswordField HP1;
    private javax.swing.JPasswordField HP2;
    private javax.swing.JTextField NC1;
    private javax.swing.JTextField NC2;
    private javax.swing.JPasswordField PC1;
    private javax.swing.JPasswordField PC2;
    private javax.swing.JTextField addDish;
    private javax.swing.JFrame addMenuFrame;
    private javax.swing.JFrame addMoneyFrame;
    private javax.swing.JTextField addPrice;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel balance1;
    private javax.swing.JFrame cancelOrderFrame;
    private javax.swing.JLabel collegeLabel;
    private javax.swing.JFrame customerDashboard;
    private javax.swing.JFrame customerFrame;
    private javax.swing.JFrame customerLogin;
    private javax.swing.JFrame customerOrders;
    private javax.swing.JFrame customerSignUp;
    private javax.swing.JLabel dishLabel;
    private javax.swing.JLabel dishLabel1;
    private javax.swing.JFrame hotelDashboard;
    private javax.swing.JFrame hotelFrame;
    private javax.swing.JFrame hotelLogin;
    private javax.swing.JFrame hotelMenuFrame;
    private javax.swing.JFrame hotelOrders;
    private javax.swing.JFrame hotelSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JFrame orderFrame;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JFrame profileFrame;
    private javax.swing.JButton searchButton;
    private javax.swing.JFrame searchFrame;
    private javax.swing.JButton searchUsersButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JFrame walletFrame;
    private javax.swing.JButton yourProfileButton;
    // End of variables declaration//GEN-END:variables

}
